Ciphertrace cash-in flow
lamassu/lamassu-server pull request #1033
Opened 2022-01-05 18:44 UTC by chaotixkilla

2022-01-20 20:34 UTC, josepfo requested changes

2022-01-20 20:34 UTC, josepfo commented on lib/cash-in/cash-in-tx.js
> +    console.log('aaaaaaaa')
Remove log

2022-01-20 20:34 UTC, josepfo commented on lib/cash-in/cash-in-tx.js
> +          console.log(fetchedWalletScore)
Remove log

2022-01-20 20:34 UTC, josepfo commented on lib/cash-in/cash-in-tx.js
> +        .then(tx => _.set('validWalletScore', _.isNil(walletScore) ? true : walletScore.isValid, tx))
if walletScore is null, we want to set validWalletScore to true?

2022-01-20 20:34 UTC, josepfo commented on lib/constants.js
> +const WALLET_SCORE_THRESHOLD = 9
Previous value was 10, is this intended?

2022-01-20 20:34 UTC, josepfo commented on lib/cash-in/cash-in-tx.js
> +        .then(tx => _.set('validWalletScore', _.isNil(walletScore) ? true : walletScore.isValid, tx))
Hmm, I think I got it. It's null when we can't access the client, and since we can't validate the wallet, we proceed normally, is that right?

2022-01-20 20:34 UTC, josepfo commented on new-lamassu-admin/src/pages/Services/Services.js
> +      : R.equals(R.view(field, data), settings.requirement)
Can you explain this one?

2022-01-20 20:34 UTC, josepfo commented on package.json
> +    "server": "nodemon bin/lamassu-server --mockSms",
Is this an intended change?

2022-01-20 20:34 UTC, josepfo commented on new-lamassu-admin/src/utils/constants.js
> +const WALLET_SCORING_DEFAULT_THRESHOLD = 9
This is set to 9 as well

2022-01-20 20:35 UTC, josepfo commented
Has conflicts

2022-01-21 18:24 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Services/Services.js
> +      : R.equals(R.view(field, data), settings.requirement)
PMed with information about this change

2022-01-22 14:26 UTC, josepfo approved these changes

2022-01-24 11:18 UTC, RafaelTaranto requested changes

2022-01-24 11:18 UTC, RafaelTaranto commented on lib/constants.js
> +const WALLET_SCORE_THRESHOLD = 9
Why do we need this? Ciphertrace is not required to be configured.

2022-01-24 11:18 UTC, RafaelTaranto commented on lib/plugins/wallet-scoring/ciphertrace/ciphertrace.js
> +  const threshold = _.isNil(account) ? WALLET_SCORE_THRESHOLD : account.scoreThreshold
If account is null and ciphertrace is not configured, we can't really send a request. It will fail and reject all transactions.

2022-01-24 11:18 UTC, RafaelTaranto commented on lib/wallet-scoring.js
> +  const pluginCode = argv.mockScoring ? 'mock-scoring' : 'ciphertrace'
We should use the same plugin interface as the other third parties. "None" is a possibility here as not all operators will configure this.

2022-01-26 09:02 UTC, merged