Fix config updates not propagating to machine without restart
lamassu/lamassu-server pull request #1052
Opened 2022-01-17 16:48 UTC by chaotixkilla

2022-01-17 21:21 UTC, josepfo approved these changes

2022-01-20 10:46 UTC, RafaelTaranto requested changes

2022-01-20 10:46 UTC, RafaelTaranto commented on lib/poller.js
>    })
I don't think we need the type nor the test anymore.

2022-01-20 10:46 UTC, RafaelTaranto commented on lib/new-settings-loader.js
> +          .then(() => t.none('NOTIFY $1:name, $2', ['reload', JSON.stringify({ type: 'reload', schema: asyncLocalStorage.getStore().get('schema'), operatorId })]))
No need for type.

2022-01-20 10:46 UTC, RafaelTaranto commented on lib/middlewares/populateSettings.js
> +    }
Same as above, no need for type or the switch anymore.

2022-01-20 17:34 UTC, merged