Get SMS notices closer to spec
lamassu/lamassu-server pull request #1099
Opened 2022-02-10 00:37 UTC by chaotixkilla

2022-02-14 16:28 UTC, siiky requested changes

2022-02-14 16:28 UTC, siiky commented on new-lamassu-admin/src/pages/OperatorInfo/SMSNotices/SMSNotices.js
> +        }}
Isn't this to delete some custom SMS template? If so, isn't a `disableSMSNotice()` missing?

2022-02-15 15:41 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/OperatorInfo/SMSNotices/SMSNotices.js
> +        }}
Oh, leaving this was an oversight on my end. Removed it

About adding a disableSMSNotice() behavior, I don't think that's needed

2022-02-15 16:16 UTC, siiky approved these changes

2022-02-16 10:09 UTC, merged