feat: cache the T&C based on their hash
lamassu/lamassu-server pull request #1188
Opened 2022-04-14 12:09 UTC by siiky

To be merged after https://github.com/lamassu/lamassu-server/pull/1164. Related: https://github.com/lamassu/lamassu-machine/pull/790.

2022-04-18 18:01 UTC, ubavic commented on lib/graphql/resolvers.js
> +const crypto = require('crypto')
This seems unnecessary

2022-04-18 18:01 UTC, ubavic commented on migrations/1649944954805-terms-and-conditions-hash.js
> +const { saveConfig, loadLatest } = require('../lib/new-settings-loader')
`loadLatest` is unnecessary

2022-04-26 17:17 UTC, RafaelTaranto requested changes

2022-04-26 17:17 UTC, RafaelTaranto commented on lib/new-settings-loader.js
> +    .update(JSON.stringify(obj))
We just need the content hash, so you don't have stringify for the rest of the settings.

2022-04-28 14:18 UTC, merged