Improve Infura network usage
lamassu/lamassu-server pull request #1247
Opened 2022-05-31 16:13 UTC by chaotixkilla

2022-06-07 16:50 UTC, josepfo reviewed
Looks good! Take a look at the wallet `coinFilter` instance, we probably can get rid of it.

2022-06-14 14:43 UTC, josepfo approved these changes

2022-07-26 12:55 UTC, RafaelTaranto requested changes

2022-07-26 12:55 UTC, RafaelTaranto commented on lib/plugins/wallet/infura/infura.js
> +}, T.minute)
We can use node-cache here. It's already being used in other places of our codebase.

2022-07-27 09:53 UTC, merged