Add script to sweep balance to a new ETH wallet
lamassu/lamassu-server pull request #1253
Opened 2022-06-09 18:06 UTC by chaotixkilla

2022-06-10 18:36 UTC, josepfo requested changes

2022-06-10 18:36 UTC, josepfo commented on bin/lamassu-eth-transfer-pending
> +      chainId: 3,
```suggestion
      chainId: 1,
```

2022-06-10 18:36 UTC, josepfo commented on lib/plugins/wallet/geth/base.js
> +        chainId: _.defaultTo(3, opts?.chainId),
```suggestion
        chainId: _.defaultTo(1, opts?.chainId),
```

2022-06-10 18:36 UTC, josepfo commented on lib/plugins/wallet/geth/base.js
> +  const common = new Common({ chain: _.defaultTo(Chain.Ropsten, opts?.chainId), hardfork: Hardfork.London })
```suggestion
  const common = new Common({ chain: Chain.Mainnet, hardfork: Hardfork.London })
```

Why do we use _.defaultTo here? I don't think the Common constructor will accept anything other than strings or enums on the chain field.

2022-06-10 18:37 UTC, josepfo commented on bin/lamassu-eth-transfer-pending
> +const paymentPrefixPath = "m/44'/60'/0'/0'"
```suggestion
```

This can be removed, right?

2022-06-12 15:09 UTC, chaotixkilla commented on lib/plugins/wallet/geth/base.js
> +  const common = new Common({ chain: _.defaultTo(Chain.Ropsten, opts?.chainId), hardfork: Hardfork.London })
It's an enum that corresponds to the chain ID. So far, it's working great, should it be removed?

2022-06-16 17:34 UTC, closed without merging