[Web3 0.20] Add script to sweep balance to a new ETH wallet
lamassu/lamassu-server pull request #1255
Opened 2022-06-13 15:57 UTC by chaotixkilla

2022-06-16 12:01 UTC, josepfo commented on bin/lamassu-eth-sweep-to-new-wallet
> +      chainId: 3,
Should be 1 instead, right?

2022-06-16 12:01 UTC, josepfo commented on bin/lamassu-eth-sweep-to-new-wallet
> +    } else {
No need for else here

2022-06-16 12:01 UTC, josepfo commented on bin/lamassu-eth-sweep-to-new-wallet
> +    console.log('Process finished successfully!')
Maybe the message `you may now execute the upgrade script again` would be better suited in this last log?

2022-06-16 12:01 UTC, josepfo commented on bin/lamassu-eth-sweep-to-new-wallet
> +      cryptoAtoms: BN(balance.times(0.99999).toFixed(0, BigNumber.ROUND_DOWN))
Can you explain this?

2022-06-16 18:02 UTC, josepfo approved these changes

2022-06-21 13:23 UTC, RafaelTaranto requested changes

2022-06-21 13:23 UTC, RafaelTaranto commented on bin/lamassu-eth-sweep-to-new-wallet
> +  })
We need to create and backup old mnemonics before moving funds.

2022-06-22 14:22 UTC, merged