Refactor getCustomer queries
lamassu/lamassu-server pull request #1259
Opened 2022-06-14 20:48 UTC by chaotixkilla

2022-06-17 12:21 UTC, siiky approved these changes

2022-06-17 12:23 UTC, siiky requested changes
Almost forgot: I suppose the `console.log`s aren't supposed to stay?

2022-06-20 09:09 UTC, siiky approved these changes

2022-10-06 17:08 UTC, RafaelTaranto requested changes

2022-10-06 17:08 UTC, RafaelTaranto commented on lib/customers.js
> +  return getCustomers({ id })
Let's leave everything as `getCustomerById()`, move this logic into the function instead of copy pasting everywhere.

2022-10-07 08:51 UTC, merged