Add l-s pre-packager
lamassu/lamassu-server pull request #1284
Opened 2022-07-05 17:15 UTC by chaotixkilla

2022-07-07 09:51 UTC, siiky approved these changes

2022-08-23 08:24 UTC, RafaelTaranto requested changes

2022-08-23 08:24 UTC, RafaelTaranto commented on build/Dockerfile
> +RUN ls -la
I don't think this is needed.

2022-08-23 08:24 UTC, RafaelTaranto commented on build/Dockerfile
> +RUN cd lamassu-server/new-lamassu-admin && npm install && npm run build
Doesn't this mean we're also shipping with the new-lamassu-admin node_modules? We can remove that folder after the build.

2022-11-01 22:54 UTC, merged