Add machine coin rates screen
lamassu/lamassu-server pull request #1300
Opened 2022-07-15 19:01 UTC by chaotixkilla

2022-07-18 12:07 UTC, siiky requested changes

2022-07-18 12:07 UTC, siiky commented on lib/plugins.js
> +    const machineScreenOpts = configManager.getAllMachineScreenOpts(settings.config)
`getMachineScreenOpts(screenName, config)` but only the config is given here (and in the wrong order).

2022-07-18 12:07 UTC, siiky commented on lib/graphql/resolvers.js
> +    configManager.getAllMachineScreenOpts(settings.config),
`addSmthInfo()` checks if the given `smth` has an `active` value and is truthy, but looking at `getAllMachineScreenOpts()` I don't think there's any.

2022-07-18 16:43 UTC, chaotixkilla commented on lib/graphql/resolvers.js
> +    configManager.getAllMachineScreenOpts(settings.config),
fixed

2022-07-19 09:20 UTC, siiky requested changes

2022-07-19 09:20 UTC, siiky commented on lib/graphql/resolvers.js
> +        _.update('screenOptions', addMachineScreenOpts(machineScreenOpts))
Isn't this `_.update()` unnecessary here? It's already in `addMachineScreenOpts()`.

2022-07-19 12:13 UTC, siiky approved these changes

2022-10-06 14:52 UTC, merged