feat: rewrite pairing totem code
lamassu/lamassu-server pull request #1319
Opened 2022-07-27 16:17 UTC by siiky

2022-07-27 19:22 UTC, chaotixkilla approved these changes

2022-12-14 09:17 UTC, RafaelTaranto requested changes

2022-12-14 09:17 UTC, RafaelTaranto commented on lib/new-admin/services/pairing.js
> +const csexp = require('lamassu-csexp')
```suggestion
const csexp = require('@lamassu/csexp')
```

2022-12-15 21:06 UTC, RafaelTaranto approved these changes

2022-12-15 21:06 UTC, merged