Show transaction sweep status
lamassu/lamassu-server pull request #1321
Opened 2022-07-28 02:45 UTC by chaotixkilla

2022-07-28 12:05 UTC, siiky approved these changes

2022-08-01 09:22 UTC, siiky approved these changes

2022-10-06 17:16 UTC, RafaelTaranto requested changes

2022-10-06 17:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/utils/constants.js
> +const SWEEPABLE_CRYPTOS = ['ETH']
USDT as well.

2022-10-06 18:25 UTC, closed without merging