Fail fast on lamassu-server default route access and SEO robots.txt
lamassu/lamassu-server pull request #1379
Opened 2022-09-16 04:27 UTC by chaotixkilla

2022-09-16 15:55 UTC, siiky approved these changes

2022-09-16 15:55 UTC, siiky commented on new-lamassu-admin/public/robots.txt
> +Disallow: /
Is this file used?

2022-10-06 17:18 UTC, RafaelTaranto requested changes

2022-10-06 17:18 UTC, RafaelTaranto commented on lib/routes.js
> +  res.status(404).json({ error: 'No such route' })
No need to return the json here. The more generic the better, so just 404 should be enough.

2022-10-06 18:27 UTC, merged