Fix settings caching
lamassu/lamassu-server pull request #1416
Opened 2022-10-18 16:18 UTC by chaotixkilla

2022-10-20 16:37 UTC, siiky requested changes

2022-10-20 16:37 UTC, siiky commented on lib/middlewares/populateSettings.js
> +        .catch(next)
This block looks like the `if (!versionId && !!needsSettingsReload[operatorId)` above (minus the `delete`). Maybe they could be merged?

```js
    if (!versionId && (!!needsSettingsReload[operatorId]) || !operatorSettings) {
    /* ... */
              if (!!needsSettingsReload[operatorId]) delete /* ... */

    /* ... */
}
```

2022-10-21 14:21 UTC, RafaelTaranto requested changes

2022-10-21 14:21 UTC, RafaelTaranto commented on lib/middlewares/populateSettings.js
> +    if (!versionId && (!!needsSettingsReload[operatorId] || !operatorSettings)) {
after exiting safely on top we don't need to check for !versionId anymore.

2022-10-21 14:21 UTC, RafaelTaranto commented on lib/middlewares/populateSettings.js
>      if (!versionId && operatorSettings) {
I don't think we need this if anymore.

2022-10-28 11:09 UTC, merged