fix: binance ticker default market fiat
lamassu/lamassu-server pull request #1477
Opened 2022-12-20 11:50 UTC by josepfo

2022-12-22 14:06 UTC, siiky approved these changes

2022-12-26 10:43 UTC, RafaelTaranto requested changes

2022-12-26 10:43 UTC, RafaelTaranto commented on lib/plugins/common/ccxt.js
> +  return ALL[serviceName].DEFAULT_FIAT_MARKET
Stuff like bitpay and pazuz ticker don't have DEFAULT_FIAT_MARKET

2022-12-26 19:56 UTC, RafaelTaranto approved these changes

2022-12-26 19:56 UTC, merged