Refactor/dev tools frontend
lamassu/lamassu-server pull request #1771
Opened 2024-11-30 09:52 UTC by RafaelTaranto

2024-12-04 12:55 UTC, siiky requested changes

2024-12-04 12:55 UTC, siiky commented on new-lamassu-admin/README.md
>  REACT_APP_TYPE_CHECK_SANCTUARY=true
This should be removed along with the above

2024-12-04 12:55 UTC, siiky commented on new-lamassu-admin/src/components/inputs/formik/PhoneNumberInput.jsx
> +  /(\+)(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)(\d{1,3}){0,1}(\d{1,3}){0,1}(\d{1,3}){0,1}(\d{1,3
`libphonenumber-js` seems to do formatting as well with `formatInternational()`/`formatNational()`

2024-12-04 12:55 UTC, siiky commented on new-lamassu-admin/src/components/layout/Sidebar.jsx
>                key={idx}
The `key` you added was probably needed, but the `key` that was already there in the child `<div>` probably isn't neeed, because it's a single `<div>`.

2024-12-04 12:55 UTC, siiky commented on new-lamassu-admin/src/pages/Customers/CustomerData.jsx
> +        }
why not remove now?

2024-12-04 12:55 UTC, siiky commented on new-lamassu-admin/src/pages/Customers/components/CreateCustomerModal.jsx
>            return R.any(it => it === true, validMap)
The `map()` could be merged into this `any()` -- a bit weird they're separate since `validMap` isn't kept afterwards...

```js
countryCodes.some(countryCode => parsePhoneNumberWithError(value, countryCode).isValid())
```

2024-12-04 12:55 UTC, siiky commented on new-lamassu-admin/src/pages/Customers/components/EditableCard.jsx
> +                        {/*)}*/}
Same as above -- why not remove now?

2024-12-04 12:55 UTC, siiky commented on new-lamassu-admin/src/pages/Transactions/DetailsCard.jsx
> +  const exchangeRate = BigNumber(fiat).div(crypto).toFixed(2, 1) // ROUND_DOWN
I know this is just UI code and that it was already there, but maybe we should avoid mixing float and bignum arithmetic. That `fiat`, for example, is converted to string, never to be used as a string (it's converted to a bignum again right after)...

2024-12-05 10:03 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/inputs/formik/PhoneNumberInput.jsx
> +  /(\+)(9[976]\d|8[987530]\d|6[987]\d|5[90]\d|42\d|3[875]\d|2[98654321]\d|9[8543210]|8[6421]|6[6543210]|5[87654321]|4[987654310]|3[9643210]|2[70]|7|1)(\d{1,3}){0,1}(\d{1,3}){0,1}(\d{1,3}){0,1}(\d{1,3
Apparently we don't even use this component, removed.

2024-12-05 10:03 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/CustomerData.jsx
> +        }
I have no idea if that works, but there's a PR removing these comments I believe.

2024-12-05 10:46 UTC, siiky approved these changes

2024-12-05 10:53 UTC, merged