Bitgo api v2
lamassu/lamassu-server pull request #223
Opened 2018-11-21 13:44 UTC by RafaelTaranto

Milestone: 7.3.x Crafty Chnemu

2018-11-21 13:45 UTC, RafaelTaranto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update BitGo module to API v2](https://trello.com/c/6FaCLmf4/710-update-bitgo-module-to-api-v2)

2018-11-21 13:47 UTC, RafaelTaranto commented on lib/plugins/wallet/bitgo/bitgo.js
> +    // TODO This was previously spendableConfirmedBalance, what happened to it on v2?
Shoud I use the minimum value between confirmedBalance and spendableBalance? Not sure what spendableConfirmedBalance means, and it not really documented on their api.

2018-11-26 21:52 UTC, RafaelTaranto commented on lib/plugins/wallet/bitgo/bitgo.js
> +    // TODO This was previously spendableConfirmedBalance, what happened to it on v2?
Some tests:

```
0.0013 cashout =>
balance: 0.09025480
confirmedBalance: 0.01075465
spendableBalance: 0.09025480

0.0013 cashout =>
balance: 0.08891092
confirmedBalance: 0
spendableBalance: 0.08891092

0.0005 cashin =>
balance: 0.08945823
confirmedBalance: 0
spendableBalance: 0.08891092
```

2018-12-03 22:17 UTC, joshmh requested changes

2018-12-03 23:01 UTC, RafaelTaranto commented on lib/plugins/wallet/bitgo/bitgo.js
> +    // TODO This was previously spendableConfirmedBalance, what happened to it on v2?
I'm converting before printout for readability.

2018-12-09 22:39 UTC, merged