Add device names to sms alerts
lamassu/lamassu-server pull request #233
Opened 2018-12-07 14:31 UTC by DatoBula

2018-12-07 14:31 UTC, DatoBula commented
![](https://github.trello.services/images/mini-trello-icon.png) [More Descriptive SMS Alerts](https://trello.com/c/XLTxpiPl/742-more-descriptive-sms-alerts)

2018-12-11 09:51 UTC, joshmh requested changes

2018-12-11 09:51 UTC, joshmh commented on lib/notifier.js
> +  return '[Lamassu] Errors reported: ' + alertTypes.join(', ') + ' (' + deviceNames.join(', ') + ')'
This isn't quite according to the Trello card spec. The idea was to have each alertType individually show which machines it's affecting, not to list all machines affected by all alerts in the end.

2018-12-12 15:03 UTC, joshmh requested changes

2018-12-12 15:03 UTC, joshmh commented on lib/notifier.js
> +  const alertTypes = _.map(function (el) {
Use arrow notation.

2018-12-12 15:03 UTC, joshmh commented on lib/notifier.js
> +    return alertType.codeDisplay + ' (' + alertType.machineName + ') '
Some alerts are global and don't have machineNames. What happens in that case?

2018-12-14 13:27 UTC, joshmh requested changes

2019-01-04 16:21 UTC, merged