Truncate/trim server tables
lamassu/lamassu-server pull request #274
Opened 2019-04-25 02:15 UTC by RafaelTaranto

2019-04-25 02:15 UTC, RafaelTaranto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Periodically truncate server logs](https://trello.com/c/OysPau04/150-periodically-truncate-server-logs)

2019-04-30 17:02 UTC, joshmh requested changes

2019-04-30 17:02 UTC, joshmh commented on lib/plugins.js
> +    logs.clearOldLogs()
Should return the promise.

```
return logs.clearOldLogs()
```

2019-04-30 17:02 UTC, joshmh commented on lib/plugins.js
> +    db.none(`UPDATE server_events SET created=now() WHERE event_type=$1;
Should return the promise.

2019-05-12 12:46 UTC, merged