feat: machine status page WIP feedback needed
lamassu/lamassu-server pull request #339
Opened 2019-12-02 15:30 UTC by mautematico

This PR uses ExpandableTable, and reuses Transactions styles to avoid repeating, so it depends on #336 (already rebased).

- adds some machine details to /api/machines endpoint
- exposes machines/:machineId/actions/:actions on the API
- adds a couple of missing icons
- adds expandableTable to show machine status
- registers machine-status on the router

TODO:
- add onClick to action buttons; I need feedback on this:
- expose 'shutdown' action

> React Hook "useAxios" is called in 'reboot' function which is neither a React function component or a custom React Hook function

2019-12-04 10:15 UTC, RafaelTaranto requested changes

2019-12-04 10:15 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/MachineDetailsCard.js
> +                      {machine.statuses.map((_status, index) => <span key={index} />)}
I think you can use `(...[, index]) => ` to avoid naming status

2019-12-04 10:15 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/MachineDetailsCard.js
> +                        onClick={reboot}
shouldn't this be shutdown?

2019-12-04 10:15 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/Status.js
> +    color: '#ff7311',
Don't we have a named color for this? We should.

We might not need the three themed objects, I'm thinking we can have one and a class to change label color.

2019-12-04 10:15 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/MachineDetailsCard.js
> +          <div className={classnames(classes.col, classes.col2)} style={{ background: '#ebefff', width: '2px' }} />
same thing with the color here.

2019-12-04 10:15 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/MachineDetailsCard.js
> +          <div className={classnames(classes.col, classes.col2)} style={{ background: '#ebefff', width: '2px' }} />
also we should prevent using the "style" prop, can't we use a class here?

2019-12-04 10:15 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/MachineDetailsCard.js
> +                      &nbsp;
We should prevent using this espaced sequence, we can do the same thing with css.

2019-12-04 10:15 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/MachineStatus.js
> +  ]
Luis will upload a new way of using this component shortly

2019-12-17 08:54 UTC, mautematico commented
closed in favor of https://github.com/lamassu/lamassu-server/pull/344

2019-12-17 08:54 UTC, closed without merging