feat: add third party services page
lamassu/lamassu-server pull request #345
Opened 2019-12-17 14:34 UTC by lcsfelix

2019-12-17 15:36 UTC, lcsfelix commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create 3rd party services page](https://trello.com/c/SJAJeejV/127-create-3rd-party-services-page)

2019-12-18 15:10 UTC, RafaelTaranto requested changes

2019-12-18 15:10 UTC, RafaelTaranto commented on new-lamassu-admin/package.json
> +    "react-scripts": "^3.2.0",
no reason to change this, undo package.json and package-lock.json changes.

2019-12-18 15:10 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/inputs/formik/TextInput.js
> -export default TextInputFormik
this is a breaking change for screens using this component, you should create new components for PhoneNumberInputFormik, SecretInputFormik

2019-12-18 15:10 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/single-row-table/SingleRowTable.js
> + */
remove this

2019-12-18 15:10 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/Infura.js
> +    }
Handle submit should make a call to post the new config, it should be the same for all forms on this page.

2019-12-18 15:10 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/Services.js
> +  }
This looks big enough to get its own file, I'll write a small style guide for us.

2019-12-18 15:10 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/EditService.js
> +  })
This gets triggered at the wrong time, we should make the call explicit and only call on the form handle submit.

2019-12-18 15:10 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/Twilio.js
> +      component: PhoneNumberInputFormik
I don't think we should force them to write a number here, there's a bug fix open about how twilio accepts named phone numbers.

2019-12-20 12:28 UTC, lcsfelix commented on new-lamassu-admin/src/components/single-row-table/SingleRowTable.js
> + */
Why? It's a bit complex, I'd think it's a good idea to leave some sort of documentation.

2019-12-20 16:50 UTC, lcsfelix commented on new-lamassu-admin/src/pages/Services/Twilio.js
> +      component: PhoneNumberInputFormik
Should the input still detect a phone number and apply masking or should it just be a simple `TextInputFormik`?

2019-12-21 14:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/single-row-table/SingleRowTable.js
> + */
Oh, looks like a commented out piece of code. 

Why is all of this wrapped on the object? Might as well pass them as separate props. I also don't see category being used

2019-12-21 14:19 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/Twilio.js
> +      component: PhoneNumberInputFormik
I think it should just be a TextInputFormik. Bringing that up in the design chat.

2020-01-09 13:16 UTC, RafaelTaranto requested changes

2020-01-09 13:16 UTC, RafaelTaranto commented on lib/new-settings-loader.js
> +  const newState = _.assign(currentState, config)
Why the change here?

2020-01-09 13:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/inputs/formik/TextInput.styles.js
> +import typographyStyles from '../../typography/styles'
We have absolute imports now, so whenever it's outside of the current folder you should go with it.

`src/styling/variables` instead of `../../../styling/variables`

same for the other one.

2020-01-09 13:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/single-row-table/SingleRowTable.js
> +import typographyStyles from '../typography/styles'
Make them absolute.

2020-01-09 13:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/Bitgo.js
> +import SecretInputFormik from '../../components/inputs/formik/SecretInput'
Same as above

2020-01-09 13:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/aux.js
> +    : ''
I don't think this works. 

test case: `smallword`

response: `smallwor(...)mallword`

2020-01-09 13:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/EditService.js
> +              }
Any reason to use this format instead of plain `{ key: value }`?

2020-01-09 13:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/Services.js
> +  const useStyles = makeStyles(styles)
This should be outside of the component function.

2020-01-09 13:16 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/Services.js
> +    return saveConfig({ variables: { config: { accounts: newAccounts } } })
I don't get this one, why the complex structure?

2020-01-10 13:16 UTC, RafaelTaranto approved these changes
lgtm

2020-01-20 17:04 UTC, merged