feat: add terms & conditions page
lamassu/lamassu-server pull request #359
Opened 2020-01-21 13:19 UTC by lcsfelix

2020-01-21 13:21 UTC, lcsfelix commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the terms and conditions screen](https://trello.com/c/Wa0lscuJ/153-create-the-terms-and-conditions-screen)

2020-01-22 09:59 UTC, RafaelTaranto requested changes

2020-01-22 09:59 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/OperatorInfo/OperatorInfo.js
> +  // const [selected, setSelected] = useState(CONTACT_INFORMATION)
Why is this commented out?

2020-01-22 09:59 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/OperatorInfo/TermsConditions.js
> +          })}
Move this to their own objects.

2020-01-22 09:59 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/OperatorInfo/TermsConditions.js
> +  const classes = useStyles()
Move this to the top of the Component. Generally hooks should be the first thing called within the component function.

2020-01-22 18:16 UTC, RafaelTaranto approved these changes

2020-01-24 13:36 UTC, joshmh commented
After merging some other PRs this PR now has conflicts. @lcsfelix can you resolve them?

2020-02-17 21:46 UTC, merged