feat: add cashboxes screen [WIP]
lamassu/lamassu-server pull request #373
Opened 2020-02-12 11:01 UTC by mautematico

2020-02-18 10:26 UTC, mautematico commented
![Screenshot_2020-02-18 Lamassu Admin(3)](https://user-images.githubusercontent.com/1238928/74727452-ccf34d80-5206-11ea-937b-45fa4b9bbc42.png)
![Screenshot_2020-02-18 Lamassu Admin(2)](https://user-images.githubusercontent.com/1238928/74727454-cd8be400-5206-11ea-8faf-6e291525646a.png)
![Screenshot_2020-02-18 Lamassu Admin(1)](https://user-images.githubusercontent.com/1238928/74727455-ce247a80-5206-11ea-955b-3f2fc16f36c9.png)
![Screenshot_2020-02-18 Lamassu Admin](https://user-images.githubusercontent.com/1238928/74727456-ce247a80-5206-11ea-9b78-acb9f766e515.png)

2020-02-27 10:21 UTC, mautematico commented
![Screenshot_2020-02-27 Lamassu Admin(5)](https://user-images.githubusercontent.com/1238928/75435409-95785580-5918-11ea-9f75-ee54277089d2.png)

2020-02-27 10:23 UTC, mautematico commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the cashbox screen](https://trello.com/c/2EJJMU25/37-create-the-cashbox-screen)

2020-02-27 13:01 UTC, RafaelTaranto requested changes

2020-02-27 13:01 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/cashboxes-table/Table.js
> +import { makeStyles } from '@material-ui/core/styles'
Why not just use the default table? There's no need for virtualization here and its mostly copy paste. There should be a better way to do it.

2020-02-27 13:01 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.js
> +// import { tomato, zodiac } from '../../../styling/variables'
This doesn't work because it's already being imported.

If we need to import with `../` better to just import from `src/`, just like the previous imports

2020-02-27 13:01 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.js
> +})
Create a file for this

2020-02-27 13:01 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/Cashboxes.js
> +          overrides: { top: {}, bottom: {} }
If this is hardcoded why not integrate it to the component?

2020-02-27 13:01 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/maintenance/Cashboxes.js
> +      alert(JSON.stringify(errorMessage))
Add a todo here and at the other alert, this should not be final.

2020-03-13 08:55 UTC, mautematico commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.js
> +})
done

2020-03-13 08:55 UTC, mautematico commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.js
> +// import { tomato, zodiac } from '../../../styling/variables'
fixed

2020-03-13 09:43 UTC, mautematico commented on new-lamassu-admin/src/components/cashboxes-table/Table.js
> +import { makeStyles } from '@material-ui/core/styles'
Fixed. Will do the same for the cashout-table

2020-03-13 10:11 UTC, mautematico commented on new-lamassu-admin/src/pages/maintenance/Cashboxes.js
> +          overrides: { top: {}, bottom: {} }
Not exactly hardcoded, but a safe default that will eventually be modified back and forth; If it's okay, I'll add a TODO here and try to come back with a better solution.

2020-05-09 17:56 UTC, RafaelTaranto approved these changes

2020-05-09 18:57 UTC, merged