fix: notifications screen fixes
lamassu/lamassu-server pull request #411
Opened 2020-07-16 00:50 UTC by liordino

fix: increased width of inputs so they doesn't cut off text

fix: reenabled the cash-out display component with 500 notes max bot and top

2020-07-16 00:51 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Notifications screen fixes](https://trello.com/c/jgIBB6Cv/145-notifications-screen-fixes)

2020-07-17 16:46 UTC, RafaelTaranto commented
@liordino >fix: reenabled the cash-out display component with 500 notes max bot and top

I'm not seeing this one here.

2020-07-18 20:02 UTC, liordino commented
> @liordino >fix: reenabled the cash-out display component with 500 notes max bot and top
> 
> I'm not seeing this one here.

Hey! I think I missunderstood this one. I added a comment on it's card with a question.

2020-07-27 09:09 UTC, RafaelTaranto requested changes
Waiting on the cashbox component.

2020-08-06 09:57 UTC, RafaelTaranto requested changes

2020-08-06 09:57 UTC, RafaelTaranto commented on lib/new-admin/config/accounts.js
> -const _ = require('lodash/fp')
Something looks wrong here. I don't see why this is in the commit given that this line doesn't exist in dev.

2020-08-06 09:57 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Notifications/sections/FiatBalanceAlerts.js
> +    : 0
Probably better to do 

` 100 * (data?.fiatBalanceCassette1 ?? 0) / max`

Instead of the ternary if, same applies for the second cassette

2020-08-10 16:39 UTC, RafaelTaranto approved these changes

2020-09-02 10:29 UTC, merged