fix: cash out fixes
lamassu/lamassu-server pull request #418
Opened 2020-07-29 10:04 UTC by mautematico

fix: on and off should have a fixed width
fix: fist screen should be two p
fix: autofocus on fields after next
fix: spacing
fix: button position
fix: make the denominations a dropdown
fix: fiat should shown input suffix
fix: wizard should have splash image
fix: add missing warning icon
fix: eslint

2020-07-29 10:06 UTC, mautematico commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cash out fixes](https://trello.com/c/pzG3UMPP/142-cash-out-fixes)

2020-07-30 14:38 UTC, RafaelTaranto requested changes

2020-07-30 14:38 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Cashout/WizardSplash.js
> +        '& > svg': {
There's no need for the child selectors, just create a new class and put the className on the element you want.

2020-07-30 14:38 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Cashout/WizardStep.styles.js
> +      top: -32
No need for child selectors here either.

2020-07-30 14:38 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Cashout/WizardStep.styles.js
> +      }
nor here.

2020-08-13 09:55 UTC, RafaelTaranto approved these changes

2020-09-18 16:09 UTC, RafaelTaranto approved these changes

2020-09-20 13:26 UTC, merged