[WIP] Create a input number component
lamassu/lamassu-server pull request #421
Opened 2020-08-06 02:21 UTC by liordino

feat: created a number input component (base and formik)

fix: replace numeric TextInput fields on the Cashout, Commissions,
Cashboxes, Notifications, Operator Info and Terms & Conditions pages

2020-08-06 02:21 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a input number component](https://trello.com/c/yCWQjz7m/174-create-a-input-number-component)

2020-08-10 16:54 UTC, RafaelTaranto requested changes

2020-08-10 16:54 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +        decimalPlaces: 0
We should allow three decimal places here.

2020-08-10 16:54 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +        decimalPlaces: 0
three decimal places here as well

2020-08-10 16:54 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +      decimalPlaces: 0
same as above

2020-08-10 16:54 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +      decimalPlaces: 0
same as above

2020-08-12 08:34 UTC, RafaelTaranto approved these changes

2020-09-02 10:32 UTC, merged