feat: custom tooltip instead of browser tooltip
lamassu/lamassu-server pull request #422
Opened 2020-08-17 09:13 UTC by mautematico

fix: remove default browser tooltip
fix: rename HelpTooltip into Tooltip
feat: allow custom tooltip element
fix: open cashout fudgefactor help tooltip on click
feat: edit and delete (editabletable) custom tooltip
feat: custom tooltip on single field editables
feat: SingleRowTable custom tooltip
feat: custom tooltip on modal close button
fix: operatorinfo custom tooltip
feat: confirmdialog custom close tooltip
fix: eslint

2020-08-17 09:14 UTC, mautematico commented
![](https://github.trello.services/images/mini-trello-icon.png) [New admin server tooltips](https://trello.com/c/5i4EmNFq/162-new-admin-server-tooltips)

2020-08-20 17:05 UTC, RafaelTaranto requested changes
is the `pointerEvents: 'none'` thing still needed after removing title from all the svgs?

2020-08-21 06:26 UTC, mautematico commented
I tried it and it's not needed anymore, so I reverted that.

2020-08-21 08:06 UTC, RafaelTaranto approved these changes

2020-09-02 10:57 UTC, merged