Create migration from old config to new
lamassu/lamassu-server pull request #424
Opened 2020-08-18 00:22 UTC by liordino

2020-08-18 00:22 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create migration from old config to new](https://trello.com/c/HKZowKPG/164-create-migration-from-old-config-to-new)

2020-08-24 18:24 UTC, RafaelTaranto requested changes

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +  }
This can be replaced with `_.mapKeys(it => replacements[it])` (not tested code)

this won't be needed because of the bitgo change.

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +    ...migrateAccounts(accounts)
better to just return a plain object on these methods and do:

```
config: migrateConfig(config),
accounts: migrateAccounts(accounts)
```

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +  }
If it's only the casing that's changing I think it's better to rename it on the new admin, this is actually a bug since the bitgo module expects upper case coins to work.

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +  if (accounts.twilio) accountsProps.push(['twilio', accounts.twilio])
Instead of doing all of this the whole method will become:

``` js
const accountArray = ['bitgo', 'bitstamp'] // plus all other accounts
return _.pick(accountArray)(accounts)
```

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +const ALL_MACHINES = 'all machines'
better to make this `const ALL_MACHINES =  'ALL_MACHINES'`

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +  }
No longer being used.

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +  const allMachines = getAllMachines(config).sort()
No longer being used.

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +  }
Maybe change to:
`const areArraysEquals = (arr1, arr2) => _.isEmpty(_.xor(arr1, arr2))`

2020-08-24 18:24 UTC, RafaelTaranto commented on lib/config-migration.js
> +        return f
This is pretty hard to understand. Some things you can do to make this clearer:

1. Try to make it step by step. For instance do only the machineScoped.map and create a variable for that. Afterwards you can concat in another variable.

2. Names are pretty explanatory, but it's too long for comfort. When we're reading this we only need some context if the code shows intent. 

``` js
// machineAndCryptoScopedPlusCryptoScopedCommissionsOverrides changed to withCryptoScoped
// cryptosAlreadyScopedWithThisFieldMachine changed to coinsToRemove or toRemove
```

3. Doing it more functionally (with the help of lodash) can help breaking things into smaller chunks and make intent clearer.

We can break logic into pretty bite sized chunks that are not that hard to follow:

``` js


const getMachine = _.get('scope.machine')
const getCrypto = _.get('scope.crypto')

const filteredMachineScoped = _.map(it => {
     const filterByMachine = _.filter(_.includes(getMachine(it)))
     const flattenCoins =  _.compose(_.flatten, _.map(getCrypto))
     const diffAllCryptos = _.compose(_.diference(ALL_CRYPTOS))

     const unrepeatedCryptos = _.compose(diffAllCryptos, flattenCoins, filterByMachine)(withCryptoScoped) 

     return _.set('scope.crypto', unrepeatedCryptos)(it)
)(machineScoped)

```

Note how even flattenCoins and diffAllCryptos can be moved to the outside of the function since they don't require any context. It would make the function a 3 liner.

2020-08-26 02:31 UTC, liordino commented on lib/config-migration.js
> +        return f
Way better! Thanks!

2020-09-16 23:31 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a migration to update the machine names on the db](https://trello.com/c/1DpEXWcL/191-create-a-migration-to-update-the-machine-names-on-the-db)

2020-09-18 16:06 UTC, RafaelTaranto requested changes

2020-09-18 16:06 UTC, RafaelTaranto commented on lib/new-settings-loader.js
> +const NEW_SETTINGS_LOADER_SCHEMA_VERSION = 2
Wasn't this already merged in another PR? There's something strange here.

2020-09-18 16:06 UTC, RafaelTaranto commented on lib/config-migration.js
> +  }
Check if active and threshold are set before creating the trigger

2020-09-18 16:06 UTC, RafaelTaranto commented on lib/config-migration.js
> +    cashDirection = 'both'
On this file you don't need all of this. Just set it straight on the return statement

2020-09-20 22:46 UTC, liordino commented on lib/new-settings-loader.js
> +const NEW_SETTINGS_LOADER_SCHEMA_VERSION = 2
Yeah, it's already on dev. Dunno why it's considered a change here

2020-09-21 08:23 UTC, RafaelTaranto requested changes

2020-09-21 08:23 UTC, RafaelTaranto commented on lib/config-migration.js
> +
I don't think we want this. There can be other requirements active without a sms threshold. What I meant on the my comment was to test both *VerificationActive and *Threshold for every IF of the triggers creation logic.

2020-09-25 10:07 UTC, merged