Locale overrides should only allow one row per machine
lamassu/lamassu-server pull request #425
Opened 2020-08-18 01:52 UTC by liordino

2020-08-18 01:53 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Locale overrides should only allow one row per machine](https://trello.com/c/5IvfE8nD/190-locale-overrides-should-only-allow-one-row-per-machine)

2020-08-19 10:57 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Locales/Locales.js
> +
This wont work. 

- empty overrides table break the page.
- already existing overrides won't show the machine when being edited.

Take a look at how the FiatBalanceOverrides does it. Better to just follow that logic.

2020-08-20 18:49 UTC, RafaelTaranto requested changes

2020-08-20 18:49 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Locales/helper.js
> +            findSuggestion(it, machineData)
Probably better to do

```
R.concat(it?.machine ? [it.machine] : [])(suggestionFilter...)
```

After the changes on Autocomplete the code checks for id to match a option, so I don't think we need to fetch it within the machineData.

2020-08-20 18:49 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Locales/helper.js
> +  )
Better to use https://ramdajs.com/docs/#differenceWith

2020-08-24 08:50 UTC, RafaelTaranto approved these changes

2020-09-02 11:03 UTC, merged