feat: Prevent leaving the page without saving
lamassu/lamassu-server pull request #431
Opened 2020-08-25 15:01 UTC by liordino

fix: make all fields required on the Terms & Conditions page if Show on
screen is enabled

fix: enable/disable the Terms & Conditions form based on the Show on
screen toggle

fix: replaced deactivated field with plain text when not editing

fix: make de non editable text content field scrollable

style: make it follow the same style as the other screens, with the edit
button and links to save and cancel

feat: created Prompt component to avoid leaving pages without saving

feat: applied component to the editable table

feat: applied component to the Cashout, Commissions, Locales, Cashboxes,
Notifications, CryptoBalanceOverrides and Wallet pages

feat: applied component to the ContactInfo and ReceiptPrinting pages

refactor: export the default prompt message to be used in other contexts

fix: applied prompt component to the Operator Info pages

fix: create routes for the operator info components

feat: applied the Prompt component to the Contact Info and Receipt pages

feat: applied the Prompt component to the Terms & Conditions page

2020-08-25 15:01 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent leaving the page without saving](https://trello.com/c/fqVxcOWq/189-prevent-leaving-the-page-without-saving)

2020-09-18 13:56 UTC, RafaelTaranto requested changes

2020-09-18 13:56 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/editableTable/Table.js
> +
Remove the console.logs

2020-09-18 13:56 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/booleanPropertiesTable/BooleanPropertiesTable.js
> +                        // />
Remove comments

2020-09-18 13:56 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/booleanPropertiesTable/BooleanPropertiesTable.js
> +                        />
Move the BooleanCell component to within this file, also make it really simple like:

```js
(name) => {
  const { values } = useFormikContext()
  values[name] ? <TrueIcon/> : <FalseIcon/>
}
```

It doesn't need to be a formik field.

2020-09-18 13:56 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/tables/BooleanCell.js
> +  value ? <TrueIcon name={name} /> : <FalseIcon name={name} />
remove this component.

2020-09-18 13:56 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/tables/formik/BooleanCell.js
> +  return <BooleanCell name={name} value={value === 'true'} {...props} />
remove this component.

2020-09-18 13:56 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/tables/formik/index.js
> +export { BooleanCell }
remove this file

2020-09-21 08:17 UTC, RafaelTaranto approved these changes

2020-09-21 11:45 UTC, merged