fix: Editing/saving fixes
lamassu/lamassu-server pull request #432
Opened 2020-08-30 20:10 UTC by liordino

feat: table add button is now hidden when adding/editing

feat: disable every other action on editable table when editing/adding

feat: hide add button instead of disabling it when can't add

feat: disable every other action when adding/editing on the commissions
page

feat: disable every other action when adding/editing on the locales
page

feat: disable every other action when adding/editing on the
notifications page

feat: disable save buttons while waiting for server response on tables
and editable numbers

2020-08-30 20:10 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Editing/saving fixes](https://trello.com/c/qgKzDCE3/188-editing-saving-fixes)

2020-09-18 15:35 UTC, RafaelTaranto requested changes

2020-09-18 15:35 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/editableTable/Table.js
> +    // TODO: maybe create a setAdding argument would be better?
Eh, this is fine as is. Remove the TODO and fix the conflics

2020-09-21 08:19 UTC, RafaelTaranto approved these changes

2020-09-22 21:28 UTC, merged