fix: commissions screen fixes
lamassu/lamassu-server pull request #434
Opened 2020-09-09 01:51 UTC by liordino

fix: don't allow negative values on the commissions forms

feat: add an all machines option to the commissions overrides

fix: added cash-in and cash-out icons to main and override table headers

feat: filter out already overriden machine-coin combinations

fix: fix error when there's no machine selected yet

2020-09-09 01:52 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Commissions screen fixes](https://trello.com/c/zjR0cCy2/173-commissions-screen-fixes)

2020-09-18 15:29 UTC, RafaelTaranto requested changes

2020-09-18 15:29 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +  __typename: 'Machine'
I don't think we need __typename here

2020-09-18 15:29 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +  cryptoCurrencies: '',
Why did you need to change from empty array to ''? Isn't cryptoCurrencies a select multiple?

2020-09-21 08:18 UTC, RafaelTaranto approved these changes

2020-09-21 11:43 UTC, merged