fix: validation and input widths
lamassu/lamassu-server pull request #435
Opened 2020-09-11 01:02 UTC by liordino

fix: don't allow negative values on the commissions forms

feat: add an all machines option to the commissions overrides

fix: added cash-in and cash-out icons to main and override table headers

feat: filter out already overriden machine-coin combinations

fix: fix error when there's no machine selected yet

fix: cash-out fields now accepts only positive values

fix: add max values for fields on Cashout, Commissions, Notifications

fix: disable adding on the Locales overrides when all of the machines
are already overriden

2020-09-11 01:03 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validation and input widths](https://trello.com/c/PCwztF9J/194-validation-and-input-widths)

2020-09-18 15:25 UTC, RafaelTaranto requested changes
Lets wait for https://github.com/lamassu/lamassu-server/pull/434/files since there's some unrelated code here.

2020-09-22 08:57 UTC, RafaelTaranto approved these changes

2020-09-22 08:57 UTC, RafaelTaranto commented
@joshmh Better to squash this one on merge.

2020-09-25 10:05 UTC, merged