fix: v7.5 - 'Company number' should be text, not numeric
lamassu/lamassu-server pull request #440
Opened 2020-09-25 01:46 UTC by liordino

fix: allow text on company number

fix: data wasn't updated after saving

fix: fixed switches on all of the operator info pages

2020-09-25 01:47 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [v7.5 - 'Company number' should be text, not numeric](https://trello.com/c/cNHLswLM/223-v75-company-number-should-be-text-not-numeric)

2020-10-06 19:15 UTC, RafaelTaranto commented
We're waiting on another PR before taking a look at this one again

2020-10-11 16:45 UTC, RafaelTaranto requested changes

2020-10-11 16:45 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/OperatorInfo/ReceiptPrinting/ReceiptPrinting.js
> +            checked={receiptPrintingConfig.active || false}
Why is the `|| false` needed on the switches?

2020-10-14 17:29 UTC, RafaelTaranto approved these changes

2020-10-15 19:30 UTC, merged