fix: Fiat currency on locales showing empty option
lamassu/lamassu-server pull request #445
Opened 2020-09-30 20:21 UTC by liordino

fix: filter out the empty code currencies from the list on locales

2020-09-30 20:21 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fiat currency on locales showing empty option](https://trello.com/c/nervZZbf/213-fiat-currency-on-locales-showing-empty-option)

2020-10-06 19:55 UTC, RafaelTaranto requested changes

2020-10-06 19:55 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Locales/helper.js
> +        options: currencyData?.filter(c => c.code !== ''),
Move the filter to the massageCurrencies server-side code.

2020-10-09 08:43 UTC, RafaelTaranto approved these changes

2020-10-09 09:09 UTC, merged