Fix: Machine status fixes
lamassu/lamassu-server pull request #447
Opened 2020-10-01 20:14 UTC by liordino

fix: machine status layout bugs

fix: reboot icon looks cropped

fix: confirm dialog layout

fix: Status chip background colors

fix: detailed machine status layout

fix: machine detailed status layout

fix: machine status article links, status chip size

fix: confirmDialog for all machine actions

fix: confirm dialog on every action. reload when success

fix: verbose input label

fix: display software version and machine model

fix: eslint fixes

fix: removed machine version and update button

fix: get machines statuses from ping

chore: removed the support articles until they're ready

fix: reset value and error states when closing the confirm dialog

fix: removed unused info from the machine table

styles: fixed styles in the machine details card

chore: moved styles to another file

fix: fixed the version gql property

2020-10-01 20:15 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Machine status fixes](https://trello.com/c/nERdgEIJ/144-machine-status-fixes)

2020-10-09 10:04 UTC, RafaelTaranto requested changes

2020-10-09 10:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/MachineDetailsCard.styles.js
> +    }
Make .li its own class here. We want to avoid nesting logic to the max, there's no reason for it.

Do the same thing for the `a`

2020-10-09 10:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/MachineDetailsCard.js
> +      // TODO: custom onActionSuccess needs to be passed down from the machinestatus table
What is this todo?

2020-10-09 10:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/MachineDetailsCard.js
> +const supportArtices = [
Add a 
```
TODO new-admin
```
For the other articles.

2020-10-09 10:04 UTC, RafaelTaranto commented on lib/machine-loader.js
> +      }
Mentioned this on another review, but we don't really want to show both "Fully functional" and "Stuck". If it's stuck it can't be fully functional.

2020-10-11 16:47 UTC, RafaelTaranto approved these changes

2020-10-16 18:56 UTC, RafaelTaranto approved these changes

2020-10-20 19:06 UTC, merged