Fix: Make every field of the notifications page optional
lamassu/lamassu-server pull request #451
Opened 2020-10-06 21:09 UTC by liordino

fix: make table fields show a '-' instead of an empty string when the
col content is null

fix: make all notifications fields optional

fix: make the notifications overrides fields valid only if the machine/
cryptocurrency and at least one of the other options are filled

2020-10-06 21:09 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make every field of the notifications page optional](https://trello.com/c/LW3sGru0/238-make-every-field-of-the-notifications-page-optional)

2020-10-09 08:45 UTC, RafaelTaranto approved these changes

2020-10-09 08:46 UTC, RafaelTaranto requested changes

2020-10-09 08:46 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/editableTable/Row.js
> +    view = it => (!it ? '-' : it.toString()),
Lets leave with empty string for now.

2020-10-11 16:45 UTC, RafaelTaranto approved these changes

2020-10-15 19:24 UTC, merged