[WIP] feat: Feature/create customer compliance subscreen
lamassu/lamassu-server pull request #465
Opened 2020-10-21 01:20 UTC by liordino

2020-10-21 01:20 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Customer page fixes](https://trello.com/c/gUHs4oAl/264-customer-page-fixes)

2020-10-21 01:21 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the customer compliance subscreen](https://trello.com/c/pxjRHSYI/263-create-the-customer-compliance-subscreen)

2020-10-25 10:03 UTC, RafaelTaranto requested changes

2020-10-25 10:03 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/IdCardPhotoCard.js
> +      // className={classes.idCardPhotoCard}
remove the comment.

2020-10-26 12:42 UTC, RafaelTaranto approved these changes

2020-10-26 16:04 UTC, merged