WIP: Revoke tokens screen
lamassu/lamassu-server pull request #467
Opened 2020-10-22 11:26 UTC by chaotixkilla

2020-10-26 12:12 UTC, RafaelTaranto requested changes

2020-10-26 12:12 UTC, RafaelTaranto commented on lib/new-admin/admin-server.js
> +  return login.register(req)
It's better to pass down only the needed params instead of letting 'login' handle the http req logic.

2020-10-26 12:12 UTC, RafaelTaranto commented on lib/new-admin/graphql/schema.js
> +    userTokens(browser: String!, os: String!): [UserToken]
You can just fetch all tokens and ignore the browser and os.

2020-10-26 12:12 UTC, RafaelTaranto commented on migrations/1603438527057-add-browser-os-info.js
> +    'ALTER TABLE user_tokens ADD COLUMN os_version text',
We probably want to save the user_agent as a whole and do the parsing on the front-end project for display only purposes.

2020-10-26 12:12 UTC, RafaelTaranto commented on new-lamassu-admin/src/utils/browser-os.js
> +const parser = require('ua-parser-js')
Use import instead of require.

2020-10-26 12:12 UTC, RafaelTaranto commented on new-lamassu-admin/src/utils/browser-os.js
> +}
We won't need this.

2020-10-26 12:12 UTC, RafaelTaranto commented on new-lamassu-admin/src/utils/browser-os.js
> +module.exports = { getRequestIP, getInformation }
use export instead of module.exports

2020-10-26 12:12 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/TokenManagement/TokenManagement.js
> +import * as browserOS from 'src/utils/browser-os'
import only the needed function

2020-10-26 12:12 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/TokenManagement/TokenManagement.js
> +      </div>
This can be replaced by TitleSection.

2020-10-26 16:53 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the "revoke tokens" screen](https://trello.com/c/LjwtOo2p/276-create-the-revoke-tokens-screen)

2020-11-12 16:12 UTC, RafaelTaranto approved these changes

2020-11-12 22:03 UTC, merged