feat: Open configuration popups on the wallet page
lamassu/lamassu-server pull request #472
Opened 2020-10-24 13:20 UTC by liordino

feat: open configuration popup when selecting a non-configured third
party service on the wallets page

2020-10-24 13:20 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Open configuration popups on the wallet page](https://trello.com/c/QovhmttA/239-open-configuration-popups-on-the-wallet-page)

2020-10-25 10:06 UTC, RafaelTaranto requested changes

2020-10-25 10:06 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Wallet/Wallet.js
> +// TODO: should I use the save config and send the config as it is when saving an account?
Nope, this is fine. You can remove this comment.

2020-10-25 10:06 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Wallet/helper.js
> +        onChange
Ticker's don't use third party services.

2020-10-26 10:14 UTC, RafaelTaranto approved these changes

2020-10-26 16:01 UTC, merged