fix: More machine status fixes
lamassu/lamassu-server pull request #473
Opened 2020-10-25 16:31 UTC by liordino

fix: fixed the expanded component not closing when redirecting from 'Add machine'

fix: use useEffect to correctly fix the not closing expanded row

fix: pass added machine id to machine status via History props instead
of url

fix: avoid page reloading on confirmed actions

2020-10-25 16:32 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Machine status fixes](https://trello.com/c/Guaxp6fM/291-machine-status-fixes)

2020-10-26 10:13 UTC, RafaelTaranto requested changes

2020-10-26 10:13 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/MachineDetailsCard.js
> +      confirmActionDialogOpen && setRenameActionDialogOpen(false)
these are flipped

2020-10-26 12:43 UTC, RafaelTaranto approved these changes

2020-10-26 16:02 UTC, merged