fix: Replace extracted Country info in admin's Customer page with State/Province, add birthdate
lamassu/lamassu-server pull request #481
Opened 2020-10-28 01:46 UTC by liordino

fix: replaced country info with state/province and added birth date on
the id data card

2020-10-28 01:46 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace extracted Country info in admin's Customer page with State/Province, add birthdate](https://trello.com/c/EKXJBFff/297-replace-extracted-country-info-in-admins-customer-page-with-state-province-add-birthdate)

2020-10-28 15:43 UTC, RafaelTaranto requested changes

2020-10-28 15:43 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/IdDataCard.js
> +      display: ifNotNull(rawDob, moment.utc(rawDob).format('YYYY-MM-D')),
We probably want DD here instead of just D

2020-10-29 08:34 UTC, RafaelTaranto approved these changes

2020-10-30 10:20 UTC, merged