fix: Fiat balance cassette amount alerts not triggering
lamassu/lamassu-server pull request #492
Opened 2020-11-01 16:08 UTC by liordino

fix: removed the attempts to use the bignumber.js lib with null values

2020-11-01 16:08 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fiat balance cassette amount alerts not triggering](https://trello.com/c/5ZlzMTy0/328-fiat-balance-cassette-amount-alerts-not-triggering)

2020-11-01 17:45 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Low crypto balance alert not triggering](https://trello.com/c/5VcFArxu/325-low-crypto-balance-alert-not-triggering)

2020-11-02 11:00 UTC, RafaelTaranto approved these changes

2020-11-02 11:00 UTC, RafaelTaranto approved these changes

2020-11-02 15:13 UTC, joshmh requested changes

2020-11-02 15:13 UTC, joshmh commented on lib/plugins.js
> +    if (lowAlertThreshold && BN(fiatBalance.balance).lt(lowAlertThreshold))
Don't use a numerical value to test for null. What if it's 0?

2020-11-04 11:27 UTC, RafaelTaranto approved these changes

2020-11-04 13:06 UTC, merged