feat: Change add machine button to be according to spec
lamassu/lamassu-server pull request #525
Opened 2020-11-25 17:06 UTC by csrapr

2020-11-25 17:06 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add machine button is not up-to-spec](https://trello.com/c/BfCcrqra/400-add-machine-button-is-not-up-to-spec)

2020-11-25 18:19 UTC, RafaelTaranto requested changes

2020-11-25 18:19 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/layout/Header.js
> +              className={classes.mr}
I'm not seeing this class anywhere.

2020-11-27 14:29 UTC, RafaelTaranto approved these changes

2020-12-11 19:19 UTC, merged