feat: Add restart services button in machine admin actions
lamassu/lamassu-server pull request #526
Opened 2020-11-25 19:04 UTC by csrapr

2020-11-25 19:06 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Restart services admin action missing](https://trello.com/c/uXG1kQgU/401-restart-services-admin-action-missing)

2020-11-27 14:31 UTC, RafaelTaranto requested changes

2020-11-27 14:31 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/MachineDetailsCard.js
> +          title={`${action?.humanReadable} this machine?`}
can we change humanReadable for display?

2020-11-30 14:33 UTC, RafaelTaranto approved these changes

2020-12-11 19:18 UTC, merged