Fix/coinatmradar fix 7.5 - error 400 request response fix
lamassu/lamassu-server pull request #528
Opened 2020-11-27 18:09 UTC by csrapr

2020-11-27 18:10 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) ['Status code 400' errors related to Coin ATM Radar on v7.5](https://trello.com/c/LcDb19y6/404-status-code-400-errors-related-to-coin-atm-radar-on-v75)

2020-12-11 15:58 UTC, RafaelTaranto requested changes

2020-12-11 15:58 UTC, RafaelTaranto commented on lib/plugins.js
> -
revert this change

2020-12-11 15:58 UTC, RafaelTaranto commented on lib/coinatmradar/coinatmradar.js
> +  // console.log('%j', data)
Remove the console.log

2020-12-11 15:58 UTC, RafaelTaranto commented on lib/coinatmradar/test/coinatmradar.test.js
> +jest.mock('../../db')
requires should be grouped at the top of the file

2020-12-11 15:58 UTC, RafaelTaranto commented on lib/coinatmradar/coinatmradar.js
> +  .then(r => console.log(r.status))
this is not properly formatted, the .then should be on the next indent level

2020-12-11 16:32 UTC, RafaelTaranto approved these changes

2020-12-15 12:12 UTC, RafaelTaranto approved these changes

2020-12-15 12:12 UTC, RafaelTaranto commented
@joshmh can we squash and merge this one?

2020-12-16 14:46 UTC, merged