feat: Setup to have two servers running at the same time and seamless test the config migration
lamassu/lamassu-server pull request #529
Opened 2020-11-27 19:35 UTC by liordino

feat: changed old server ports so it can coexists with the new server

feat: removed deleted references from old server

feat: created reset and migrate mutations on gql server and
correspondent functions on new settings loader

feat: created front end for the config migration with reset and migrate
functionalities

style: add spacing between buttons

2020-11-27 19:35 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Setup to have two servers running at the same time and seamless test the config migration](https://trello.com/c/qgoaeA0L/385-setup-to-have-two-servers-running-at-the-same-time-and-seamless-test-the-config-migration)

2020-11-30 13:07 UTC, RafaelTaranto approved these changes

2020-12-01 14:53 UTC, RafaelTaranto requested changes
Commit isn't signed

2020-12-14 13:38 UTC, chaotixkilla approved these changes

2020-12-14 13:42 UTC, RafaelTaranto approved these changes

2020-12-24 20:20 UTC, merged