feat: Review the config migration code for changes and TODOs
lamassu/lamassu-server pull request #530
Opened 2020-12-01 13:33 UTC by liordino

feat: added ALL_COINS option to the commissions migration

fix: only compare arrays when both variables are arrays

fix: 'all coins' must be on a array to work

2020-12-01 13:35 UTC, liordino commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review the config migration code for changes and TODOs](https://trello.com/c/C98r2zDC/384-review-the-config-migration-code-for-changes-and-todos)

2020-12-01 14:55 UTC, RafaelTaranto requested changes
commit isn't signed

2020-12-14 16:54 UTC, csrapr approved these changes

2020-12-14 16:55 UTC, csrapr approved these changes

2020-12-15 12:14 UTC, RafaelTaranto approved these changes

2021-01-05 11:08 UTC, RafaelTaranto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Review the config migration code for changes and TODOs](https://trello.com/c/C98r2zDC/384-review-the-config-migration-code-for-changes-and-todos)

2021-01-05 11:09 UTC, closed without merging