feat: Customer transactions fetching with dataloader library
lamassu/lamassu-server pull request #531
Opened 2020-12-01 14:33 UTC by csrapr

2020-12-01 14:37 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Move customer transactions fetching to use the DataLoader library](https://trello.com/c/JSI7iE1s/421-move-customer-transactions-fetching-to-use-the-dataloader-library)

2020-12-02 10:35 UTC, RafaelTaranto requested changes

2020-12-02 10:35 UTC, RafaelTaranto commented on lib/new-admin/transactions.js
> +  })
Looks like this is a _.groupBy

2020-12-02 10:35 UTC, RafaelTaranto commented on lib/new-admin/transactions.js
> +module.exports = { batch, getCustomerTransactions, single, cancel, getCustomerTransactionsBatch }
I don't think we need the vanilla getCustomerTransactions

2020-12-02 10:35 UTC, RafaelTaranto commented on lib/new-admin/transactions.js
> +  const transactions = await packager([...cashIns, ...cashOuts])
Hmm, this is not ideal since the queries will be sequential and not parallel, let's keep using promise on this server for now.

2020-12-02 10:35 UTC, RafaelTaranto commented on lib/new-admin/transactions.js
>  function getCustomerTransactions (customerId) {
Not using this anymore.

2020-12-02 11:25 UTC, hellypi commented
Another change I need to do, add space between function name and the parentheses, like so `functionName () {}`

2020-12-04 12:15 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard v1](https://trello.com/c/f5hr310c/425-dashboard-v1)

2020-12-04 12:27 UTC, RafaelTaranto requested changes

2020-12-04 12:27 UTC, RafaelTaranto commented on lib/new-admin/transactions.js
> +  where c.id::text LIKE ANY($1)
This should be a `where c.id in ($1)'

2020-12-04 12:27 UTC, RafaelTaranto commented on lib/new-admin/transactions.js
> +  where c.id::text LIKE ANY ($1)
same as above

2020-12-11 16:00 UTC, RafaelTaranto approved these changes

2020-12-11 19:23 UTC, merged