Feat/transitions between screens
lamassu/lamassu-server pull request #543
Opened 2020-12-21 12:46 UTC by jsousa127

2020-12-21 20:17 UTC, RafaelTaranto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Transition animation for changes pages](https://trello.com/c/wOFvkJi1/377-transition-animation-for-changes-pages)

2020-12-21 20:18 UTC, RafaelTaranto approved these changes

2020-12-23 18:00 UTC, joshmh requested changes

2020-12-23 18:00 UTC, joshmh commented on new-lamassu-admin/src/components/layout/Header.js
> +                  to={{ pathname: it.route, state: { prev: prev } }}
```suggestion
                  to={{ pathname: it.route, state: { prev } }}
```

2020-12-23 19:38 UTC, jsousa127 commented on new-lamassu-admin/src/components/layout/Header.js
> +                  to={{ pathname: it.route, state: { prev: prev } }}
I didn't notice it was actually a change in the pull request until now so i manually updated it.

2020-12-23 19:41 UTC, merged