Feat: Add notifications to dashboard page
lamassu/lamassu-server pull request #554
Opened 2021-01-07 15:36 UTC by csrapr

2021-01-07 15:36 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard V2 PT1: Re-introduce the notification card](https://trello.com/c/NWGq3w3F/433-dashboard-v2-pt1-re-introduce-the-notification-card)

2021-02-05 13:53 UTC, RafaelTaranto requested changes

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/cash-out/cash-out-atomic.js
> +
Seems like this is not being used here.

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/cash-out/cash-out-atomic.js
> +  })
This change was not really needed, did you forget to add a notifier function here?

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/notifier/sms.js
> +      _.map('machineName', entry[1]),
we're not doing trailing commas.

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/notifier/sms.js
> +      _.map('cryptoCode', entry[1]),
same as above

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/notifier/utils.js
> +  deviceAlerts,
no trailling commas

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/poller.js
> +const notifier = require('./notifier/index')
this came back for some reason

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/routes.js
> +  console.log("SANCTIONS TRIGGERED")
remove console.log

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/plugins.js
>    return {
Look like every change here was styling related. Can you undo this?

2021-02-05 13:53 UTC, RafaelTaranto commented on lib/ticker.js
> +module.exports = { getBtcRates, getRates }
this came back

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/typography/styles.js
> +const styles = {
you can undo this

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/CustomerProfile.js
> +import { /*  getFormattedPhone,  */ getName } from './helper'
undo the changes on this file

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/CustomersList.js
> +import {
undo changes on this file

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/CustomerDetails.js
> -import { getFormattedPhone, getName } from '../helper'
same here

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/helper.js
>  const getFormattedPhone = (phone, country) => {
same here

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Dashboard/Alerts/Alerts.js
> +                console.log('aaaa')
remove console.log

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Dashboard/SystemPerformance/Graphs/PercentageChart.js
> +      return <Label1 className={classes.label}>{` ${value}%`}</Label1>
can't this be `{value}%`?

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Dashboard/SystemPerformance/Graphs/PercentageChart.js
> +    if (value > 15) {
I would rather to have a explicit return here instead of returning nothing:

```js
if (value <= 15) return
```

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Dashboard/SystemPerformance/Graphs/PercentageChart.js
> +          value < 5 && value > 0 ? classes.other : null
You can create object with logic to pass down to 'classnames'

```js
const percentageClasses = {
  [classes.percentageBox]: true,
  [classes.inColor]: true,
  [classes.other]: value < 5 && value > 0
}

...

clasnames(percentageClasses)

```

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Dashboard/SystemPerformance/Graphs/PercentageChart.js
> +        style={{ width: `${value}%`, marginRight: 4 }}>
you can pass value as a variable on `useState()`, move this to a class.

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Dashboard/SystemPerformance/Graphs/PercentageChart.js
> +        style={{ width: `${100 - value}%` }}>
same as above

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Machines/MachineComponents/Transactions/CopyToClipboard.js
> +import { makeStyles } from '@material-ui/core/styles'
wasn't this removed? I think this is true for all of the changes in the `Transactions` folder

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Notifications/sections/CryptoBalanceOverrides.js
> +const LOW_BALANCE_KEY = 'cryptoLowBalance'
undo this change.

2021-02-05 13:53 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Transactions/DetailsCard.styles.js
> +const styles = {
undo this change

2021-02-05 13:53 UTC, RafaelTaranto commented on package-lock.json
>      "xmlchars": {
undo the package-lock changes as well.

2021-02-05 17:38 UTC, RafaelTaranto requested changes

2021-02-05 17:38 UTC, RafaelTaranto commented on lib/ticker.js
> +const axios = require('axios')
not being used

2021-02-05 17:38 UTC, RafaelTaranto commented on lib/cash-out/cash-out-atomic.js
undo changes on this file, again looks like formatting only

2021-02-05 17:38 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Transactions/DetailsCard.styles.js
> -    // rework this into a proper component
No need for this comment

2021-02-05 17:38 UTC, RafaelTaranto commented on package-lock.json
> +    "call-bind": {
undo package-lock changes.

2021-02-05 18:50 UTC, RafaelTaranto approved these changes

2021-02-05 18:59 UTC, merged