Fix: make OperatorInfo receipts table reset values on cancel
lamassu/lamassu-server pull request #556
Opened 2021-01-07 18:16 UTC by csrapr

2021-01-07 18:16 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Boolean tables not updating when clicking 'cancel'](https://trello.com/c/bkH397sE/501-boolean-tables-not-updating-when-clicking-cancel)

2021-01-07 18:43 UTC, chaotixkilla approved these changes

2021-01-07 20:21 UTC, RafaelTaranto requested changes

2021-01-07 20:21 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/booleanPropertiesTable/BooleanPropertiesTable.js
> +    const initialValues = R.mergeRight(defaultValues, data)
Why the merge right? Might as well default to

2021-01-08 17:14 UTC, RafaelTaranto requested changes

2021-01-08 17:14 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/booleanPropertiesTable/BooleanPropertiesTable.js
> +import _ from 'lodash/fp'
Hmm, just noticing that this was using lodash, we don't even have lodash on the front-end build scripts. Replace this with ramda.

2021-01-08 17:14 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/booleanPropertiesTable/BooleanPropertiesTable.js
> +      elements.map(it => [it.name, data[it.name] || null])
Might as well use `??` instead of `||` here.

2021-01-11 11:03 UTC, RafaelTaranto approved these changes

2021-01-11 20:32 UTC, closed without merging