Refactor express entry point and implement per-operator cache
lamassu/lamassu-server pull request #563
Opened 2021-01-13 19:43 UTC by csrapr

2021-01-13 19:43 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor l-s and l-a-s entrypoint express config](https://trello.com/c/bn5QnYep/488-refactor-l-s-and-l-a-s-entrypoint-express-config)

2021-01-13 19:44 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a per-operator config cache on l-s](https://trello.com/c/yPUjtmT9/489-create-a-per-operator-config-cache-on-l-s)

2021-01-20 01:33 UTC, jsousa127 commented on lib/middlewares/filterOldRequests.js
> +const THROTTLE_CLOCK_SKEW = 60 * 1000
Maybe change this to `const THROTTLE_CLOCK_SKEW = CLOCK_SKEW`

2021-01-20 01:36 UTC, jsousa127 commented on lib/middlewares/pair.js
> +    .then(valid => {
I think `isValid` is more appropriate

2021-01-20 13:52 UTC, jsousa127 commented on lib/routes/pollingRoutes.js
> +}
Maybe it better to use the ternary operator here:

    return (!terms.active || !terms.text)
        ? null
        : {
            active: terms.active,
            title: terms.title,
            text: nmd(terms.text),
            accept: terms.acceptButtonText,
            cancel: terms.cancelButtonText
        }`

2021-01-20 13:55 UTC, jsousa127 commented on lib/routes/termsAndConditionsRoutes.js
> +}
This function is equal to other one i commented on, right? Maybe you can reuse it, or else change to ternary operator

2021-01-20 13:58 UTC, jsousa127 requested changes
I left some comments.

2021-01-22 17:04 UTC, RafaelTaranto requested changes

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/middlewares/operatorId.js
> +}
This should load the file on initialization and then always return the sasme value.

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/middlewares/pair.js
> +  console.log('pair')
remove console.log

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/middlewares/pair.js
> +}
this is copy pasted into a lot of things, move this function to a routes/errors.js

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/middlewares/pair.js
> +}
Isn't this a endpoint? It should be under a route, not really middleware

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/middlewares/populateDeviceId.js
> +  const crypto = require('crypto')
I know it's required like this historically, but move the require to the top of the file.

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/routes.js
> -  '/verify_coupon'
verify_coupon should be on the configRequiredRoutes

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/routes/ownAuthorizationRoutes.js
> +router.get('/ca', ca)
These should be on the main routes file, this ownAuthorizationRoutes doesn't do anything really.

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/routes/localAppRoutes.js
> +  settingsCache.clearCache()
this is not really implemented

2021-01-22 17:04 UTC, RafaelTaranto commented on lib/routes.js
> -app.post('/verify_coupon', verifyCoupon)
missing verify_coupon request

2021-03-17 19:24 UTC, RafaelTaranto approved these changes

2021-03-18 11:04 UTC, joshmh requested changes

2021-03-18 11:04 UTC, joshmh commented on lib/middlewares/settingsCache.js
> +const getCache = (operatorId) => state.settingsCache[operatorId] ? state.settingsCache[operatorId].cache : null
Might be a good idea to check for null or blank operatorId. Otherwise, if it's not passed in properly we could cross-pollute operator info.

2021-03-19 14:04 UTC, merged