[WIP] Notification page changes
lamassu/lamassu-server pull request #569
Opened 2021-01-20 12:24 UTC by csrapr

2021-01-20 12:24 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Notification page changes](https://trello.com/c/tCQbVo1H/516-notification-page-changes)

2021-01-20 12:25 UTC, csrapr commented
We'll have to cherry-pick the commits later, starting with 
@csrapr Feat: add notification center row in notification settings table 
& onwards

2021-02-03 12:20 UTC, chaotixkilla requested changes
Some very minor stuff. There are some comments throughout the code, I'm not sure which ones were temporary and which were to inform future people working on the code, so I marked none.

2021-02-03 12:20 UTC, chaotixkilla commented on lib/notifier/index.js
> +    const readyToNotify = tx.direction === 'cashIn' || (tx.direction === 'cashOut' && rec.isRedemption)
Why not reuse the variable `isCashOut`?
```suggestion
    const isCashOut = tx.direction === 'cashOut'

    // for notification center
    const directionDisplay = isCashOut ? 'cash-out' : 'cash-in'
    const readyToNotify = !isCashOut || (isCashOut && rec.isRedemption)
```

2021-02-03 12:20 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/action/wrench/zodiac.svg
> +</svg>
Not sure if supposed, but .svg files are missing the newline at the end

2021-02-03 15:24 UTC, csrapr commented
Again, first commit that "counts" is:
@csrapr
Feat: add notification center row in notification settings table

2021-02-09 13:56 UTC, chaotixkilla approved these changes

2021-02-09 13:56 UTC, chaotixkilla commented on lib/notifier/queries.js
> +  const sql = `INSERT INTO notifications (id, type, message, detail) values ($1, $2, $3, $4)`
`values` should be capitalized, but it is not a problem
```suggestion
  const sql = `INSERT INTO notifications (id, type, message, detail) VALUES ($1, $2, $3, $4)`
```

2021-02-09 14:27 UTC, RafaelTaranto requested changes

2021-02-09 14:27 UTC, RafaelTaranto commented on lib/machine-loader.js
> +const checkStuckScreen = require('./notifier').checkStuckScreen
Hmm, I'm not a fan of this style of import. Can't you do

```js
const {checkPings, checkStuckScreen} = require('./notifier')
```

2021-02-09 14:27 UTC, RafaelTaranto commented on lib/machine-loader.js
> +const checkStuckScreen = require('./notifier').checkStuckScreen
Also all of the svg changes are unneeded.

2021-02-09 14:42 UTC, RafaelTaranto approved these changes

2021-02-14 23:20 UTC, joshmh requested changes

2021-02-14 23:20 UTC, joshmh commented on lib/blacklist.js
> +  notifierQueries.clearBlacklistNotification(cryptoCode, address).catch(console.error)
Are we ever doing something with these errors other than printing to log? If not, ``notifierQueries`` should take care of it.

2021-02-15 23:17 UTC, merged