Fix coupon codes tooltip button submitting forms
lamassu/lamassu-server pull request #579
Opened 2021-01-29 16:45 UTC by chaotixkilla

2021-01-29 16:46 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Clicking the info box in the coupon codes screen saves entry](https://trello.com/c/A4NjY5eX/539-clicking-the-info-box-in-the-coupon-codes-screen-saves-entry)

2021-02-02 10:19 UTC, RafaelTaranto requested changes

2021-02-02 10:19 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/Tooltip.js
> +    console.log(event)
remove the console.log

2021-02-02 15:23 UTC, RafaelTaranto approved these changes

2021-02-04 13:17 UTC, merged

2021-02-05 18:32 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [ERC-20: Add USDT](https://trello.com/c/snrPYh1G/549-erc-20-add-usdt)