Remove status section of the machine status table
lamassu/lamassu-server pull request #581
Opened 2021-02-03 16:55 UTC by chaotixkilla

2021-02-03 16:55 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update the expandable machine status table](https://trello.com/c/2oKmk5VH/548-update-the-expandable-machine-status-table)

2021-02-03 20:20 UTC, csrapr requested changes

2021-02-03 20:20 UTC, csrapr commented on new-lamassu-admin/src/pages/Maintenance/MachineDetailsCard.js
>      <>
we can remove this unnecessary fragment while we're at it

2021-02-09 10:33 UTC, RafaelTaranto approved these changes

2021-02-14 23:27 UTC, merged