Fix: comma and dot separators for nums in Dashboard footer and Funding
lamassu/lamassu-server pull request #587
Opened 2021-02-09 00:31 UTC by csrapr

2021-02-09 00:31 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Unit / decimal separators and precision in Dashboard, Funding panels](https://trello.com/c/IHIvTHfD/558-unit-decimal-separators-and-precision-in-dashboard-funding-panels)

2021-02-09 12:11 UTC, josepfo approved these changes

2021-02-09 14:28 UTC, RafaelTaranto approved these changes

2021-02-14 23:26 UTC, joshmh requested changes

2021-02-14 23:26 UTC, joshmh commented on new-lamassu-admin/src/pages/Dashboard/Footer/Footer.js
>        .decimalPlaces(2)
Is this necessary? Should be handled by ``toFormat``.

2021-02-20 00:09 UTC, merged