Enable cashbox by default
lamassu/lamassu-server pull request #588
Opened 2021-02-09 17:43 UTC by chaotixkilla

2021-02-09 17:44 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cashbox should always be enabled](https://trello.com/c/WhUb2bzK/559-cashbox-should-always-be-enabled)

2021-02-09 20:17 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Reject expired IDs](https://trello.com/c/TXOi8uy4/565-reject-expired-ids)

2021-02-10 11:09 UTC, josepfo approved these changes

2021-02-11 10:32 UTC, RafaelTaranto requested changes

2021-02-11 10:32 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/editableTable/Row.js
> +  const shouldStripe = stripeWhen && stripeWhen(values)
Have you make sure that other places that contain stripe aren't being broken by this change?

2021-02-11 10:32 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +
Why do we need this?

2021-02-11 14:33 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +
We don't actually. Fixed

2021-02-12 10:01 UTC, RafaelTaranto approved these changes

2021-02-14 23:15 UTC, merged