Fix commission list horizontal overflow
lamassu/lamassu-server pull request #589
Opened 2021-02-09 18:37 UTC by chaotixkilla

2021-02-09 18:37 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Commission list table with unneeded horizontal overflow](https://trello.com/c/lfHXXSnw/560-commission-list-table-with-unneeded-horizontal-overflow)

2021-02-10 10:49 UTC, josepfo approved these changes

2021-02-11 10:30 UTC, RafaelTaranto requested changes

2021-02-11 10:30 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Commissions/components/CommissionsList.js
> +    overflowX: 'hidden',
Can't we just reduce the width of the cryptocurrencies column?

2021-02-12 10:00 UTC, RafaelTaranto approved these changes

2021-02-15 23:20 UTC, merged