Fix dropdown issues after changes
lamassu/lamassu-server pull request #594
Opened 2021-02-10 18:54 UTC by chaotixkilla

2021-02-10 18:54 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Third party services bitgo issue with new dropdown](https://trello.com/c/Mg7DKJCP/567-third-party-services-bitgo-issue-with-new-dropdown)

2021-02-13 09:48 UTC, RafaelTaranto requested changes

2021-02-13 09:48 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Services/FormRenderer.js
> +
remove console.log

2021-02-13 09:48 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Cashout/Wizard.js
> +      }
will this work even if we don't have options? There's a scenario where this should be a simple InputNumber, not sure where that's implemented.

2021-02-15 18:37 UTC, RafaelTaranto approved these changes

2021-02-16 14:04 UTC, merged