Compliance triggers improvements
lamassu/lamassu-server pull request #596
Opened 2021-02-12 16:06 UTC by chaotixkilla

2021-02-12 16:06 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance triggers improvements](https://trello.com/c/J92ASMeq/571-compliance-triggers-improvements)

2021-02-13 10:16 UTC, RafaelTaranto approved these changes

2021-02-16 11:41 UTC, joshmh requested changes

2021-02-16 11:41 UTC, joshmh commented on new-lamassu-admin/src/pages/Triggers/Wizard.js
> +  const newTextParts = newText.split('⎼⎼⎼⎼⎼ ')
Explain what this is about.

2021-02-16 18:54 UTC, joshmh approved these changes

2021-02-16 21:22 UTC, RafaelTaranto approved these changes

2021-02-17 11:10 UTC, merged