Fix: cash cassettes fixes
lamassu/lamassu-server pull request #612
Opened 2021-02-19 16:13 UTC by csrapr

2021-02-19 16:13 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cash cassettes fixes](https://trello.com/c/DVOJangP/581-cash-cassettes-fixes)

2021-02-23 13:50 UTC, chaotixkilla requested changes
Pretty much only forgotten comments

2021-02-23 13:50 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +
Is this comment still necessary?

2021-02-23 13:50 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Maintenance/CashCassettesFooter.js
> +import { makeStyles } from '@material-ui/core'
Couple of comments spread throughout this file

2021-02-23 13:50 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Maintenance/CashCassettesFooter.styles.js
> +    // temp marginLeft until cashIn square is enabled
Same here

2021-02-23 19:32 UTC, csrapr commented
rebased

2021-02-23 22:32 UTC, chaotixkilla approved these changes

2021-02-25 14:25 UTC, RafaelTaranto requested changes

2021-02-25 14:25 UTC, RafaelTaranto commented on lib/new-admin/bills.js
> +    })
We don't want to leave this query here. Either remove everything related to it or make it return a error, devs should not be allowed to use this.

2021-02-28 21:04 UTC, RafaelTaranto approved these changes

2021-03-07 17:34 UTC, merged