crypto dropdown stays open after selection
lamassu/lamassu-server pull request #619
Opened 2021-02-22 14:38 UTC by mrSnow95

2021-02-22 15:21 UTC, mrSnow95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Leave the dropdown open on the crypto currency dropdown](https://trello.com/c/Hxz4abTL/591-leave-the-dropdown-open-on-the-crypto-currency-dropdown)

2021-02-23 13:22 UTC, chaotixkilla requested changes

2021-02-23 13:22 UTC, chaotixkilla commented on new-lamassu-admin/src/components/inputs/base/Autocomplete.js
> +  keepOpenProp,
Shouldn't this `keepOpenProp` be also on the `<MAutoComplete>`  node? It works as it currently is, but other props are being explicitly passed on the node. It's more for consistency sake

2021-02-23 13:22 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +      width: 316,
Any specific reason for this change?

2021-03-16 19:15 UTC, closed without merging