fix: typo in admin setup wizard
lamassu/lamassu-server pull request #624
Opened 2021-02-24 19:23 UTC by josepfo

2021-02-24 19:24 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Typo in Admin Setup Wizard](https://trello.com/c/6GM5XCAc/606-typo-in-admin-setup-wizard)

2021-02-25 18:55 UTC, chaotixkilla approved these changes

2021-02-25 21:28 UTC, RafaelTaranto requested changes

2021-02-25 21:28 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Wizard/helper.js
> +    text: `From the Locales page, you can define default settings
forgot to replace page with panel, from Neals comment.

2021-02-26 13:58 UTC, RafaelTaranto approved these changes

2021-03-07 17:37 UTC, merged