Fix: unhandled rejection, notif center settings not being respected
lamassu/lamassu-server pull request #626
Opened 2021-02-25 20:02 UTC by csrapr

2021-02-25 20:02 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix unhandled rejection in the notifier module "notifyIfActive" function](https://trello.com/c/BQskO7oK/613-fix-unhandled-rejection-in-the-notifier-module-notifyifactive-function)

2021-02-28 21:09 UTC, RafaelTaranto requested changes

2021-02-28 21:09 UTC, RafaelTaranto commented on lib/notifier/index.js
> +    const notificationSettings = utils.fromNamespace('notificationCenter', configManager.getGlobalNotifications(settings.config))
Why not use configManager here?

2021-03-01 16:30 UTC, RafaelTaranto approved these changes

2021-03-07 17:40 UTC, merged