Feat: upgrade pg-promise and fix breaking changes
lamassu/lamassu-server pull request #628
Opened 2021-02-26 18:44 UTC by csrapr

2021-02-26 18:44 UTC, csrapr commented
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade pg-promise to the latest version](https://trello.com/c/AW0oHTdY/612-upgrade-pg-promise-to-the-latest-version)

2021-03-01 12:51 UTC, chaotixkilla approved these changes

2021-04-14 21:31 UTC, RafaelTaranto requested changes

2021-04-14 21:31 UTC, RafaelTaranto commented on lib/cash-out/cash-out-tx.js
> +  return db.tx({ mode }, cashOutAtomic.atomic(tx, pi, fromClient))
Maybe we can move the tx to inside cashOutAtomic. That way the configuration stays in place and we're actually leaving the file named atomic as atomic, same thing for cashIn

2021-04-16 07:59 UTC, RafaelTaranto approved these changes

2021-04-27 15:36 UTC, RafaelTaranto approved these changes

2021-05-22 17:17 UTC, merged