Disallow navigation to and blocking of anonymous customers
lamassu/lamassu-server pull request #629
Opened 2021-03-01 14:30 UTC by josepfo

2021-03-01 14:30 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Disallow navigation to, and blocking of, anonymous customer](https://trello.com/c/Y5sXv5V8/616-disallow-navigation-to-and-blocking-of-anonymous-customer)

2021-03-02 18:05 UTC, csrapr reviewed
.

2021-03-07 21:09 UTC, RafaelTaranto requested changes

2021-03-07 21:09 UTC, RafaelTaranto commented on lib/new-admin/graphql/schema.js
> +      return customers.getCustomerById(args.customerId)
It's cleaner if you do the other way around

```suggestion
      if (args.customerId === anonymous.uuid) return customers.getCustomerById(args.customerId)
      return customers.updateCustomer(args.customerId, args.customerInput, token)
      
```

2021-03-07 21:09 UTC, RafaelTaranto commented on lib/new-admin/graphql/schema.js
>      setCustomer: (root, args, context, info) => {
Also might as well desconstruct args here.

2021-03-08 21:21 UTC, RafaelTaranto approved these changes

2021-03-16 11:09 UTC, merged