Fix commission override function composition
lamassu/lamassu-server pull request #646
Opened 2021-03-16 15:21 UTC by chaotixkilla

2021-03-16 15:21 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Having no machines paired causes overrides which require machines to crash the server](https://trello.com/c/pjWBPwa0/643-having-no-machines-paired-causes-overrides-which-require-machines-to-crash-the-server)

2021-03-16 15:53 UTC, csrapr requested changes

2021-03-16 15:53 UTC, csrapr commented on new-lamassu-admin/src/pages/Commissions/helper.js
> +    : 'Unpaired machine'
like we talked: `return hasValue ? R.prop(code, hasValue) : 'Unpaired machine'`

2021-03-17 16:14 UTC, RafaelTaranto approved these changes

2021-03-18 10:59 UTC, merged