feat: relay id data photos to server
lamassu/lamassu-server pull request #648
Opened 2021-03-17 14:46 UTC by josepfo

2021-03-17 14:47 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Capture and relay ID Data stills to operator server if not parsed](https://trello.com/c/U7bZ7bNI/607-capture-and-relay-id-data-stills-to-operator-server-if-not-parsed)

2021-03-17 20:33 UTC, chaotixkilla approved these changes

2021-03-17 20:33 UTC, chaotixkilla commented on lib/customers.js
> +
An extra newline here.

Normally, I would say to remove the comments, but as it is a function which touches on lower level stuff, I like the extra comments

2021-06-25 22:19 UTC, RafaelTaranto requested changes

2021-06-25 22:19 UTC, RafaelTaranto commented on lamassu-remote-install/install
> +OPERATOR_DIR=/opt/lamassu-server/operatordata
Hmm, we might need to add this to the lamassu-install repo as well.

2021-06-25 22:19 UTC, RafaelTaranto commented on lib/customers.js
> +      console.log(dir, 'directoryyyy')
console.logs

2021-06-25 22:19 UTC, RafaelTaranto commented on lib/customers.js
> +      console.log(dirname, 'dirnaaaaaaaaaaaaaaame')
console.log

2021-06-25 22:19 UTC, RafaelTaranto commented on lib/customers.js
> +        console.log(index)
another one

2021-06-25 22:19 UTC, RafaelTaranto commented on lib/customers.js
> +  console.log(directory)
another one

2021-06-25 22:19 UTC, RafaelTaranto commented on lib/routes/customerRoutes.js
> +router.patch('/:id/dataphotos', updateIdCardData)
let's change the endpoint here to `/:id/photos/idcarddata`

2021-06-25 22:19 UTC, RafaelTaranto commented on lib/customers.js
> +  const directory = operatorDataDir + '/' + operatorId + '/' + id + '/'
```suggestion
  const directory = `${operatorDataDir}/${operatorId}/${id}/`
```

2021-06-25 22:19 UTC, RafaelTaranto commented on lib/customers.js
> +        // i.e. ../<lamassu-server-home>/<operatorid>/<customerid>/idcarddata/1.jpg
this comment is not related anymore.

2021-06-30 16:15 UTC, josepfo commented on lib/customers.js
> +        // i.e. ../<lamassu-server-home>/<operatorid>/<customerid>/idcarddata/1.jpg
why not?

2021-07-02 10:20 UTC, RafaelTaranto approved these changes

2021-07-05 11:25 UTC, merged