Implement fido auth
lamassu/lamassu-server pull request #650
Opened 2021-03-17 18:43 UTC by chaotixkilla

2021-03-17 20:34 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add fido2 auth protocol support](https://trello.com/c/5sqivfNl/491-add-fido2-auth-protocol-support)

2021-03-22 13:34 UTC, csrapr requested changes

2021-03-22 13:34 UTC, hellypi commented on lib/credentials.js
> +  const sql = `SELECT * from hardware_credentials`
uppercase from -> FROM
(same on line 16, from and where)

2021-03-22 13:34 UTC, csrapr commented on lib/new-admin/graphql/modules/userManagement.js
> +  })
since you're not doing anything in the catch block you can just put catch(console.error) instead

2021-03-22 13:34 UTC, csrapr commented on lib/new-admin/graphql/modules/userManagement.js
> +    return true
if isCodeValid is a boolean we can just do return isCodeValid otherwise we can also do return !!isCodeValid

2021-03-22 13:34 UTC, csrapr commented on lib/new-admin/graphql/modules/userManagement.js
> +    .catch(err => console.error(err))
same thing as above, .catch(console.error) also works
there are other places we can also change to this, if you decide to change

2021-03-22 13:34 UTC, csrapr commented on lib/new-admin/graphql/schema.js
> +const machineEventsByIdBatch = require("../../postgresql_interface").machineEventsByIdBatch
revert to ' instead of "

2021-03-22 13:34 UTC, csrapr commented on lib/new-admin/graphql/modules/userManagement.js
> +    users.save2FASecret(user.id, secret)
missing error catching, either here or where save2FASecret is declared, check with Rafael where it's best to catch this error

2021-03-22 13:34 UTC, csrapr commented on new-lamassu-admin/src/pages/Authentication/InputFIDOState.js
> +import { useMutation, useLazyQuery /*, useQuery */ } from '@apollo/react-hooks'
remove comment

2021-03-22 13:34 UTC, csrapr commented on new-lamassu-admin/src/pages/Authentication/ResetPassword.js
> +                </>
no need for fragment

2021-03-22 13:34 UTC, csrapr commented on new-lamassu-admin/src/pages/UserManagement/UserManagement.js
> +      // Show a popup with message 'Success'?
remove comment

2021-03-22 13:35 UTC, hellypi commented
Also needs to fix conflicting files

2021-03-24 15:40 UTC, csrapr approved these changes

2021-05-07 15:55 UTC, closed without merging