Fix cash cassettes footer shows nan
lamassu/lamassu-server pull request #656
Opened 2021-03-22 16:07 UTC by josepfo

2021-03-22 16:53 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cash-cassettes footer shows NaN if there's a machine without cash-out enabled.](https://trello.com/c/csZsCVuu/654-cash-cassettes-footer-shows-nan-if-theres-a-machine-without-cash-out-enabled)

2021-03-24 13:02 UTC, chaotixkilla approved these changes

2021-03-28 20:06 UTC, RafaelTaranto requested changes

2021-03-28 20:06 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/CashCassettesFooter.js
> +            {isValidNumber(totalInCassettes) ? totalInCassettes : 0}{' '}
I don't think this fixes it. What happens when there's a mix of cash-out and non cash-out machines? Probably better to validate on the reducer

2021-03-29 13:25 UTC, RafaelTaranto approved these changes

2021-04-14 20:59 UTC, RafaelTaranto approved these changes

2021-04-30 16:48 UTC, merged