Fix error messages compliance triggers
lamassu/lamassu-server pull request #657
Opened 2021-03-23 16:56 UTC by josepfo

2021-03-23 18:41 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Correct validation messages in Compliance triggers](https://trello.com/c/fpECT4Lh/663-correct-validation-messages-in-compliance-triggers)

2021-03-24 13:03 UTC, chaotixkilla approved these changes

2021-03-28 20:04 UTC, RafaelTaranto requested changes

2021-03-28 20:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +    )
This is complicated to read. 

```js
if (triggerType && thresholdValidator[triggerType](threshold)) return

return context.createError({
  path: 'threshold',
  message: errorMessages[triggerType](threshold)
})
```

2021-03-28 20:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +    )
same as above

2021-03-28 20:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +        console.log(message)
remove console.log

2021-03-28 20:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +        console.log(message)
remove console.log

2021-03-28 20:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +        let message = ''
Maybe it's better to have message be a array and then join the array with a , as separator. With this we can ditch the let for a const.

2021-03-28 20:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +            : message.concat(thresholdDaysMessage)
With the change above we can also remove this logic from here.

2021-03-28 20:04 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +            : message.concat(thresholdDaysMessage)
same as above

2021-03-29 13:24 UTC, RafaelTaranto requested changes

2021-03-29 13:24 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +        if (threshold.thresholdDays <= 0) return message[1]
```suggestion
        const message = []
        
        if (threshold.threshold < 0) message.push(threhsoldMessage)
        if (threshold.thresholdDays <= 0) message.push(thresholdDaysMessage)
        
        return message.join(', ')
```

2021-03-29 13:24 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Triggers/helper.js
> +        return message
same as above

2021-04-14 21:12 UTC, RafaelTaranto approved these changes

2021-04-30 16:55 UTC, merged