Feat: create relations between trades and transactions
lamassu/lamassu-server pull request #667
Opened 2021-03-26 13:59 UTC by josepfo

2021-03-26 13:59 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Record internal TX UUIDs in trades table, relay via API to exchanges' user reference fields](https://trello.com/c/orPhOEDP/642-record-internal-tx-uuids-in-trades-table-relay-via-api-to-exchanges-user-reference-fields)

2021-03-29 18:35 UTC, csrapr requested changes

2021-03-29 18:35 UTC, csrapr commented on lib/plugins.js
> +      .then(newTrade => recordTradeAndTx(newTrade.id, _tradeEntry.internalTxIdList))
This also looks like chained queries, if they are, do them inside a task or a tx (transaction) https://vitaly-t.github.io/pg-promise/Task.html

2021-03-30 14:41 UTC, csrapr approved these changes

2021-05-14 10:28 UTC, RafaelTaranto requested changes

2021-05-14 10:28 UTC, RafaelTaranto commented on lib/plugins.js
> +
```suggestion
    const partitionByDirection = _.partition(({ direction }) => direction === 'cashIn'))
    const [cashInTxs, cashOutTxs] = _.compose(partitionByDirection, _.uniqBy('internalTxId'))(filtered)
```

2021-05-14 10:28 UTC, RafaelTaranto commented on lib/plugins.js
> +      internalTxIdList,
```suggestion
      cashInTxs,
      cashOutTxs,
```

2021-05-14 10:28 UTC, RafaelTaranto commented on lib/plugins.js
> +      return recordTradeAndTx(newTrade.id, _tradeEntry.internalTxIdList, t)
```suggestion
      return recordTradeAndTx(newTrade.id, _tradeEntry, t)
```

2021-05-14 10:28 UTC, RafaelTaranto commented on lib/plugins.js
> +      .catch(error => error)
This looks useless.

2021-05-14 10:28 UTC, RafaelTaranto commented on lib/plugins.js
> +      const newTrade = await t.oneOrNone(sql)
don't use async on the server for now

2021-05-14 10:28 UTC, RafaelTaranto commented on lib/plugins.js
> +  function recordTradeAndTx (tradeId, internalTxIdList, dbTx) {
```suggestion
  function recordTradeAndTx (tradeId, { cashInTxs, cashOutTxs }, dbTx) {
```

2021-05-14 10:28 UTC, RafaelTaranto commented on migrations/1616687417371-add_internal_tx_to_trades.js
> +      cash_in_tx_id uuid REFERENCES cash_in_txs(id),
```suggestion
      tx_id uuid REFERENCES cash_in_txs(id),
```

2021-05-14 10:28 UTC, RafaelTaranto commented on migrations/1616687417371-add_internal_tx_to_trades.js
> +      cash_out_tx_id uuid REFERENCES cash_out_txs(id),
```suggestion
      tx_id uuid REFERENCES cash_out_txs(id),
```

2021-05-14 10:28 UTC, RafaelTaranto commented on lib/plugins.js
> +    }
```js
  const columnSetCashIn = new pgp.helpers.ColumnSet(['tx_id', 'trade_id'], { table: 'cashin_tx_trades' })
  const columnSetCashOut = new pgp.helpers.ColumnSet(['tx_id', 'trade_id'], { table: 'cashout_tx_trades' })

  const mapToEntry = _.map((tx, tradeId) => ({ tx_id: tx.internalTxId, trade_id: tradeId }))
  const queries = []

  if (!_isEmpty(cashInTxs)) {
    const query = pgp.helpers.insert(mapToEntry(cashInTxs), columnSetCashIn)
    queries.push(dbTx.none(query))
  }

  if (!_isEmpty(cashOutTxs)) {
    const query = pgp.helpers.insert(mapToEntry(cashOutTxs), columnSetCashOut)
    queries.push(dbTx.none(query))
  }
```

2021-05-17 09:07 UTC, RafaelTaranto approved these changes

2021-05-25 11:09 UTC, merged