feat: rbf checkbox in blockcypher settings
lamassu/lamassu-server pull request #672
Opened 2021-04-05 23:24 UTC by josepfo

2021-04-05 23:25 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add RBF toggle to blockcypher in third-party settings](https://trello.com/c/nCajAo7W/674-add-rbf-toggle-to-blockcypher-in-third-party-settings)

2021-04-06 16:55 UTC, chaotixkilla requested changes
The checkbox logic changes should only be extended towards supporting the disabled message. Any gql logic, label, wallet logic, etc, etc should only be sent to the Checkbox component as props and not be built in the component, as this will break all other uses of this component.

2021-04-07 00:54 UTC, chaotixkilla approved these changes
Much better now, everything seems fine. Good job!

2021-05-12 15:16 UTC, RafaelTaranto approved these changes

2021-05-25 09:48 UTC, merged