Cash cassettes edit wizard
lamassu/lamassu-server pull request #676
Opened 2021-04-08 22:24 UTC by chaotixkilla

2021-04-08 22:28 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the edit wizard to the cashbox screen PT1](https://trello.com/c/rdsAiK20/692-add-the-edit-wizard-to-the-cashbox-screen-pt1)

2021-04-09 19:22 UTC, csrapr approved these changes
Good stuff, that wizard 👌🏻👌🏻👌🏻

2021-05-12 15:31 UTC, RafaelTaranto requested changes

2021-05-12 15:31 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/Wizard/WizardStep.js
> +                    {steps[step - 1].fiatAmount && (
When will the step get fiatAmounts? I don't see this being used anywhere else.

2021-05-12 15:31 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/Wizard/WizardStep.js
> +    )
```suggestion
    const cassetteCount = step === 2 ? values.cassette1Count : values.cassette2Count
    const value = cassetteCount ?? cassetteInfo.amount
    R.clamp(0, 100, (100 * (value / cassetteCapacity))
```

2021-05-12 20:32 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Maintenance/Wizard/WizardStep.js
> +    )
Good idea!

2021-05-13 20:54 UTC, RafaelTaranto requested changes

2021-05-13 20:54 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +  console.log('data', data)
Remove the console.log

2021-05-14 10:29 UTC, RafaelTaranto approved these changes

2021-05-25 09:59 UTC, merged