fix: remove crypto amount rounding
lamassu/lamassu-server pull request #680
Opened 2021-04-13 16:57 UTC by josepfo

2021-04-13 16:57 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Don't round crypto amount in admin's Transactions panel](https://trello.com/c/3ZK0hj15/681-dont-round-crypto-amount-in-admins-transactions-panel)

2021-04-14 20:58 UTC, RafaelTaranto requested changes

2021-04-14 20:58 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Transactions/Transactions.js
> +        `${toUnit(new BigNumber(it.cryptoAtoms), it.cryptoCode)} ${
We don't want to remove the rounding as a whole, we should do the same as the machine does. 

Also is there even enough space here to show the additional digits?

2021-04-19 10:46 UTC, RafaelTaranto approved these changes

2021-04-30 16:52 UTC, merged