Detect machine cashbox removal
lamassu/lamassu-server pull request #681
Opened 2021-04-13 17:39 UTC by chaotixkilla

2021-04-13 17:40 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Detect and notify the server on cashbox removal](https://trello.com/c/HLRx64H5/694-detect-and-notify-the-server-on-cashbox-removal)

2021-04-13 21:14 UTC, josepfo approved these changes

2021-04-16 08:08 UTC, RafaelTaranto requested changes

2021-04-16 08:08 UTC, RafaelTaranto commented on lib/routes.js
> +app.use('/notify', cashboxRoutes)
Maybe we can start a cashbox subroute. This can be /cashbox, and the notifyRemoval /removal.

2021-05-31 18:53 UTC, RafaelTaranto approved these changes

2021-06-22 14:20 UTC, merged