Convert UI timestamps according to timezone
lamassu/lamassu-server pull request #701
Opened 2021-04-29 19:12 UTC by chaotixkilla

2021-04-29 19:12 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Output the logs with the correct timezones](https://trello.com/c/tnlsbWhh/723-output-the-logs-with-the-correct-timezones)

2021-05-03 20:43 UTC, csrapr commented on new-lamassu-admin/src/utils/timezones.js
> +const getFormattedTimezones = timezones =>
sheesh :D

2021-05-03 20:44 UTC, csrapr approved these changes

2021-05-17 10:39 UTC, RafaelTaranto requested changes

2021-05-17 10:39 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Locales/Locales.js
> +
Console.log

2021-05-17 10:39 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Machines/MachineComponents/Details.js
> +  console.log(timezone)
console.log

2021-05-17 10:40 UTC, RafaelTaranto commented
Maybe having a utils for this would help reduce duplicated code

2021-05-31 19:01 UTC, RafaelTaranto approved these changes

2021-06-22 14:46 UTC, merged