Hardware credential authentication
lamassu/lamassu-server pull request #712
Opened 2021-05-07 15:54 UTC by chaotixkilla

2021-05-07 15:55 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add fido2 auth protocol support](https://trello.com/c/5sqivfNl/491-add-fido2-auth-protocol-support)

2021-06-14 17:04 UTC, csrapr requested changes

2021-06-14 17:04 UTC, hellypi commented on lib/hardware-credentials.js
> +  const sql = `SELECT * from hardware_credentials`
```suggestion
  const sql = `SELECT * FROM hardware_credentials`
```

2021-06-14 17:04 UTC, hellypi commented on lib/hardware-credentials.js
> +  const sql = `SELECT * from hardware_credentials where user_id=$1`
```suggestion
  const sql = `SELECT * FROM hardware_credentials WHERE user_id=$1`
```

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDO2FAStrategy.js
> +const expectedOrigin = `https://${rpID}:3001`
shouldn't this be an environment variable? Seems like it's gonna break on something like digitalocean

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDO2FAStrategy.js
> +  }).then(([userDevices, user]) => {
according to pg-promise documentation, chained queries should be done in the same task (no real need for a full on transaction here).
"Task" allows us to reuse the same db connection for chained queries instead of potentially doing something like
reserve connection --> query --> drop connection back to the pool --> reserve connection --> query -->...

https://vitaly-t.github.io/pg-promise/Task.html

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDO2FAStrategy.js
> +      const options = simpleWebauthn.generateAssertionOptions({
these are also chained queries, right? If so, try to see if you can also use a task here.

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDO2FAStrategy.js
> +    }).then(async verification => {
I personally also prefer async await where possible, but check with Rafael if using async here won't break the thing we have about not using async in lamassu-server

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDO2FAStrategy.js
> +    return credentials.getHardwareCredentialsOfUser(user.id).then(async devices => {
same here about async

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDO2FAStrategy.js
> +    }).then(async verification => {
you don't seem to need the response of users.getUserById to do simpleWebauthn.verifyAttestationResponse so we can create a promise array and do Promise.all([promise1, promise2])

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDO2FAStrategy.js
> +      if (verified && attestationInfo) {
can't we invert this? if (!(verified || attestationInfo)) return // response for when not verified or atested
// rest of the code

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDOPasswordlessStrategy.js
> +const expectedOrigin = `https://${rpID}:3001`
same thing about env vars

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDOPasswordlessStrategy.js
> +    const options = simpleWebauthn.generateAttestationOptions({
try using db.task for chained queries

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDOPasswordlessStrategy.js
> +    return credentials.getHardwareCredentialsOfUser(user.id).then(devices => {
db.task

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/authentication/FIDOPasswordlessStrategy.js
> +    return credentials.getHardwareCredentialsOfUser(user.id).then(async devices => {
db task

2021-06-14 17:04 UTC, hellypi commented on lib/new-admin/graphql/modules/userManagement.js
> +      return Promise.all([credentials.getHardwareCredentialsOfUser(user.id), user.twofa_code])
you get the idea, for the rest of this review whenever you find chained queries, try to see if you can do it using db.task

2021-06-14 17:04 UTC, csrapr commented on migrations/1620335170327-hardware-credentials.js
> +      data JSONB
maybe make these fields not nullable

2021-06-14 17:04 UTC, csrapr commented on new-lamassu-admin/src/pages/Authentication/LoginState.js
> +        console.log(options)
stray console.log

2021-06-14 17:04 UTC, csrapr commented on new-lamassu-admin/src/pages/UserManagement/UserManagement.js
> +      // success ? console.log('success') : console.log('failure')
stray console.logs

2021-08-03 18:53 UTC, josepfo commented on new-lamassu-admin/src/pages/Authentication/InputFIDOState.js
> +        console.log(options)
remove console.log

2021-08-05 14:02 UTC, josepfo approved these changes

2021-11-24 18:17 UTC, RafaelTaranto requested changes

2021-11-24 18:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/UserManagement/UserManagement.js
> +    }
What does actually happen here? Does the user get logged in?

2021-11-24 18:17 UTC, RafaelTaranto commented on lib/hardware-credentials.js
> +function getHardwareCredentialsOfUser (userID) {
`getHardwareCredentialsByUserId`

2021-11-24 18:17 UTC, RafaelTaranto commented on lib/new-admin/graphql/resolvers/users.resolver.js
> +  }
Can't we use a switch to setup the options instead of everything?

Something like:
```js
     case 'FIDO2FA': {
        return { username, password }
     }
```

Also if you change the generateAssertionOptions you can always pass down all params and have the same code for everything. Actually since the options are the only thing that chance maybe generateAssertion(context, options) would be a better interface for the functions.

2021-11-24 18:17 UTC, RafaelTaranto commented on lib/new-admin/graphql/resolvers/users.resolver.js
> +      return {}
same as above

2021-11-24 18:17 UTC, RafaelTaranto commented on lib/new-admin/graphql/modules/authentication/FIDOUsernamelessStrategy.js
> +const expectedOrigin = `https://${rpID}:3001`
What's the expected origin exactly? What's running on 3001?

2021-11-24 18:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Authentication/LoginState.js
> +                I have a YubiKey
Shouldn't this be a generic text? You can ask Neal for a version of it.

2021-11-24 18:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Authentication/InputFIDOState.js
> +          <H2 className={classes.info}>Insert your Yubikey and touch it</H2>
Same issue with "Yubikey" showing here.

2021-11-24 22:55 UTC, merged