Feat: add option to reset cashbox
lamassu/lamassu-server pull request #718
Opened 2021-05-12 21:37 UTC by josepfo

2021-05-12 21:39 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add the option to reset cashbox automatically on detection or manually with the wizard](https://trello.com/c/PSEfPDa3/744-add-the-option-to-reset-cashbox-automatically-on-detection-or-manually-with-the-wizard)

2021-05-18 02:03 UTC, chaotixkilla requested changes

2021-05-18 02:03 UTC, chaotixkilla commented on lib/routes/cashboxRoutes.js
> +          console.log(cashInSettings)
Remove console.log

2021-05-18 02:03 UTC, chaotixkilla commented on lib/routes/cashboxRoutes.js
> +            return res.status(200).send({ status: 'OK' })
I pointed out on another PR, but I remember Rafael saying that l-s should opt to use `then`, instead of `async/await`, due to something related with error handling. I'll confirm this with him tomorrow.

2021-05-18 02:03 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +        </Modal>
Is this still design pending? Couldn't find a spec anywhere

2021-05-20 00:58 UTC, chaotixkilla approved these changes

2021-05-20 01:11 UTC, chaotixkilla requested changes

2021-05-20 01:11 UTC, chaotixkilla commented on lib/routes/cashboxRoutes.js
> +              .then(() => res.status(200).send({ status: 'OK' }))
This status code 200 is only being sent if the cashboxReset is set to automatic, which shouldn't happen, as it should always send 200 independently of the option.
Move line 18 outside of the if statement

2021-05-20 19:06 UTC, chaotixkilla approved these changes

2021-07-06 20:29 UTC, RafaelTaranto requested changes

2021-07-06 20:29 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.styles.js
> +    marginTop: '0px'
```suggestion
    marginTop: 0
```

2021-07-06 20:29 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.styles.js
> +    margin: '13px 0px -5px 20px'
```suggestion
    margin: [[13, 0, -5, 20]]
```

2021-07-06 20:29 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.styles.js
> +    marginRight: '12px'
```suggestion
    marginRight: 12
```

2021-07-06 20:29 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +    { display: 'Manual', code: 'Manual' }
can we change code to a string and put it on a utils?

Something like

```js
const AUTOMATIC = 'automatic'
const MANUAL = 'manual'

    { display: 'Automatic', code: AUTOMATIC },
    { display: 'Manual', code: MANUAL }
```

2021-07-06 20:29 UTC, RafaelTaranto commented on lib/routes/cashboxRoutes.js
> +        })
```suggestion
  return Promise.all([getMachine(req.deviceId), loadLatestConfig()])
    .then(([machine, config]) => {
      const cashInSettings = getCashInSettings(config)
      
      if (cashInSettings.cashboxReset !== 'Automatic') {
        return res.status(200).send({ status: 'OK' })
      }
      
      return cashbox.createCashboxBatch(req.deviceId, machine.cashbox)
        .then(() => setMachine({ deviceId: req.deviceId, action: 'emptyCashInBills' }))
        .then(() => res.status(200).send({ status: 'OK' }))
    })
```

2021-07-12 18:18 UTC, RafaelTaranto approved these changes

2021-07-13 16:09 UTC, merged