Notify cashbox removal
lamassu/lamassu-server pull request #724
Opened 2021-05-20 19:17 UTC by chaotixkilla

2021-05-20 19:19 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Notify operator on cashbox removed](https://trello.com/c/fqyEXyFB/765-notify-operator-on-cashbox-removed)

2021-05-21 22:47 UTC, josepfo requested changes

2021-05-21 22:47 UTC, josepfo commented on migrations/1621430588944-notify-cashbox-removal.js
> +          }
This condition only makes sense when migrating something from v7.4. I did the same mistake hehe
```suggestion
```

2021-07-14 13:03 UTC, josepfo commented on migrations/1621430588944-notify-cashbox-removal.js
> +
Don't we want to add these fields when the value is false as well?

2021-07-16 09:04 UTC, RafaelTaranto approved these changes

2021-07-23 19:15 UTC, joshmh commented on lib/notifier/index.js
> +      if (emailActive) promises.push(emailFuncs.sendMessage(settings, rec))
This notification logic should be general purpose for all notifications. @chaotixkilla can you create a new Trello card to generalize the logic?

2021-07-23 19:17 UTC, merged