Rework pazuz admin version
lamassu/lamassu-server pull request #748
Opened 2021-06-08 15:18 UTC by chaotixkilla

feat: add build target field to routes
feat: move towards single App.js file
fix: header component interaction with build target

2021-06-08 15:18 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rework the pazuz version of the admin](https://trello.com/c/U0b00Hs9/810-rework-the-pazuz-version-of-the-admin)

2021-06-08 22:30 UTC, csrapr requested changes

2021-06-08 22:30 UTC, csrapr commented on new-lamassu-admin/src/routing/routes.js
> +console.log('tree', tree)
stray console.log

2021-06-08 22:30 UTC, csrapr commented on new-lamassu-admin/src/routing/routes.js
>  // import ConfigMigration from 'src/pages/ConfigMigration'
can you check if we can we remove this since we're editing this file anyway, please?

2021-06-10 10:58 UTC, RafaelTaranto approved these changes

2021-06-23 14:15 UTC, merged