Changes to customer page design
lamassu/lamassu-server pull request #755
Opened 2021-06-11 03:13 UTC by chaotixkilla

fix: subpage button design
fix: remove unnecessary table title
chore: update icons
fix: customer profile labels

2021-06-11 03:13 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design fixes on customer profile screen](https://trello.com/c/0TLpRu3K/822-design-fixes-on-customer-profile-screen)

2021-06-14 20:37 UTC, josepfo approved these changes

2021-06-15 23:11 UTC, RafaelTaranto requested changes

2021-06-15 23:11 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/TransactionsList.js
>            </H4>
Probably better to hide the h4 as a whole instead of rendering it empty when it has data.

2021-06-28 08:23 UTC, RafaelTaranto approved these changes

2021-07-05 11:20 UTC, merged