feat: create db table and store operator id
lamassu/lamassu-server pull request #757
Opened 2021-06-12 18:36 UTC by josepfo

2021-06-12 18:37 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a table for operator IDs](https://trello.com/c/Gx6uxhGL/772-create-a-table-for-operator-ids)

2021-06-13 21:11 UTC, chaotixkilla requested changes

2021-06-13 21:11 UTC, chaotixkilla commented on migrations/1623413776161-create-operator-ids.js
> +        description TEXT NOT NULL)`
The `)` should be on the next line

2021-06-13 21:11 UTC, chaotixkilla commented on migrations/1623413776161-create-operator-ids.js
> +      const sql2 = `INSERT INTO operator_ids (id, description) VALUES ('${operatorId}','mnemonic' )`
A bit of formatting here 
```suggestion
      const sql2 = `INSERT INTO operator_ids (id, description) VALUES ('${operatorId}', 'mnemonic')`
```

2021-11-23 01:12 UTC, chaotixkilla approved these changes

2021-11-24 17:51 UTC, merged