Fix: design fixes on notifications screen
lamassu/lamassu-server pull request #763
Opened 2021-06-17 17:12 UTC by josepfo

2021-06-17 17:13 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design fixes on notifications screen](https://trello.com/c/JacvJ4OV/832-design-fixes-on-notifications-screen)

2021-06-18 15:26 UTC, chaotixkilla requested changes

2021-06-18 15:26 UTC, chaotixkilla commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.js
> +  const classes = cashboxClasses({ percent, cashOut, inFiatBalanceAlerts })
I'm not really a fan of having a flag for a specific screen, as we might use that same behavior in the future, and the variable name shouldn't be tied to a specific screen. My suggestion is to call this flag something like `shouldApplyColorVariance`/`shouldApplyColorGradient` (I don't like the gradient one as much, as we're not working with gradients)

2021-06-18 15:26 UTC, chaotixkilla commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.styles.js
> +const colorPicker = ({ percent, cashOut, inFiatBalanceAlerts }) => {
This flag

2021-06-18 15:26 UTC, chaotixkilla commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.js
> +  const classes = cashboxClasses({ percent, cashOut, inFiatBalanceAlerts })
Also, default value should be `false` when this flag is not specified in props. You can make the default value `true`, but the flag would need to be called something as `dontApplyColorVariance`

2021-06-18 15:26 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Notifications/sections/FiatBalanceAlerts.js
> +                  inFiatBalanceAlerts={true}
This here. Also, I believe you can get away with omitting `={true}`, and just call `applyColorVariant` or whatever name you decide better fits the flag's purpose

2021-06-18 15:26 UTC, chaotixkilla commented on new-lamassu-admin/src/components/inputs/cashbox/Cashbox.js
> +  const classes = cashboxClasses({ percent, cashOut, inFiatBalanceAlerts })
Ah, noticed you're calling a pre-existing flag here. I guess you can ignore the variable name change

2021-06-23 18:55 UTC, RafaelTaranto approved these changes

2021-06-24 10:53 UTC, merged