Analytics screen
lamassu/lamassu-server pull request #764
Opened 2021-06-18 14:53 UTC by chaotixkilla

2021-06-18 14:54 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Analytics PT1](https://trello.com/c/3IyFGuPy/828-analytics-pt1)

2021-06-24 19:12 UTC, josepfo requested changes
Great job, looks awesome!
Just a few details, according to the spec the percentage on each OverviewEntry should be bold and without empty space between the icon. Also, the background on the Select drop-down should have a dark color.

2021-06-24 19:12 UTC, josepfo commented on new-lamassu-admin/src/pages/Analytics/Analytics.js
> +  // )
Did you miss this code or intend to use it in the future?
```suggestion
```

2021-07-05 20:47 UTC, josepfo approved these changes

2021-09-22 09:17 UTC, RafaelTaranto requested changes
Also has conflicts

2021-09-22 09:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Analytics/Analytics.js
> +const MONTH = 30 * 24 * 60 * 60 * 1000
Don't we use this elswhere?

2021-09-22 09:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Analytics/Graph.js
> +const MINUTE = 60 * 1000
We do hehe, add this to a consts file on utils.

2021-09-22 09:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Analytics/Graph.js
> +  const GRAPH_MARGIN = useMemo(
Is there a reason for this to be a memoized react component? Why not a simple object?

2021-09-22 09:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Analytics/Graph.js
> +    ]
I'm pretty sure we can get this from a lib, is the react project using any date libs?

2021-09-22 09:17 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Analytics/Analytics.js
> +  }
This would also get pretty simplified with a lib.

2021-10-11 01:28 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Analytics/Graph.js
> +  const GRAPH_MARGIN = useMemo(
Mostly for optimization purposes, as the `useEffect` hook is calling a function, which "needs" to be wrapped in `useCallback`, which calls these objects, which should be memoized ideally I think. Might not matter as much to require optimization

2021-11-19 10:03 UTC, closed without merging