Fix gender data parsing
lamassu/lamassu-server pull request #767
Opened 2021-06-21 17:27 UTC by chaotixkilla

2021-06-21 17:29 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Gender not shown on Customer Panel](https://trello.com/c/StvtZQfH/837-gender-not-shown-on-customer-panel)

2021-06-21 17:46 UTC, RafaelTaranto requested changes

2021-06-21 17:46 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/IdDataCard.js
> +  console.log('customer', customerData)
console.log

2021-06-21 17:46 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/IdDataCard.js
> +        R.path(['gender'])(idData) ?? R.path(['sex'])(idData)
Since we're doing this might as well change the BC parser to use gender, also leave a comment here explaning why we need this.

2021-06-26 09:00 UTC, RafaelTaranto requested changes

2021-06-26 09:00 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/IdDataCard.js
> +  }
I would rather have this in the machine code alongside the specific parser for US.

2021-06-26 09:00 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Customers/components/IdDataCard.js
> +        R.path(['gender'])(idData) ?? R.path(['sex'])(idData)
Still no comment here.

2021-06-28 14:39 UTC, merged