Fix user token revoke
lamassu/lamassu-server pull request #777
Opened 2021-06-25 16:04 UTC by chaotixkilla

2021-06-25 16:09 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Revoking admin user errors if user has modified any customer compliance types](https://trello.com/c/tFkbGlrx/855-revoking-admin-user-errors-if-user-has-modified-any-customer-compliance-types)

2021-06-28 18:15 UTC, josepfo requested changes
I prefer having SQL keywords in uppercase but it's up to you.

2021-06-28 18:15 UTC, josepfo commented on bin/lamassu-revoke
> +    const count = _.reduce((acc, v) => acc + v.length, 0, result)
```suggestion
    const count = _.sumBy(_.size, result)
```

2021-06-28 20:24 UTC, josepfo approved these changes

2021-06-29 08:56 UTC, RafaelTaranto requested changes

2021-06-29 08:56 UTC, RafaelTaranto commented on bin/lamassu-revoke
> +    return db.task('get-touched-customers', t => {
This should be a transaction

2021-06-29 08:56 UTC, RafaelTaranto commented on bin/lamassu-revoke
> +  })
This should be inside the transaction

2021-06-30 09:17 UTC, RafaelTaranto requested changes

2021-06-30 09:17 UTC, RafaelTaranto commented on bin/lamassu-revoke
> +      return t.batch([
Can't this try to delete the token before cleaning up the customer table? I don't think order is guaranteed here. Probably better to have token deletion part on a inner `then`, keep in mind that line 39 already executes the query, so even that has to be inside the `then`.

2021-06-30 14:52 UTC, RafaelTaranto approved these changes

2021-07-05 11:22 UTC, merged