feat: machine performance indicators
lamassu/lamassu-server pull request #793
Opened 2021-07-16 02:24 UTC by josepfo

2021-07-16 14:16 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Ping time, machine internet quality measurement](https://trello.com/c/Ya5LaGiN/878-2-ping-time-machine-internet-quality-measurement)

2021-07-16 18:02 UTC, chaotixkilla requested changes

2021-07-16 18:02 UTC, chaotixkilla commented on lib/plugins.js
> +  }
This is more readable indeed, but I'd prefer to maintain the formatting we have right now

2021-07-16 18:02 UTC, chaotixkilla commented on migrations/1626275844773-add-machine-network-performance.js
> +      )`
Uppercase the SQL keywords

2021-07-16 18:02 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Machines/MachineComponents/Overview.js
> +          <Label3 className={classes.label3}>Loss</Label3>
Perhaps 'Packet Loss' would be more compreensive, instead of 'Loss'?

2021-07-16 18:02 UTC, chaotixkilla commented on lib/machine-loader.js
> +  const upsert = pgp.helpers.insert(dbData, cs) + onConflict
GJ here on using prepared statements, I should be using them more as well

2021-07-23 15:57 UTC, chaotixkilla approved these changes

2021-08-30 10:47 UTC, RafaelTaranto approved these changes

2021-09-07 16:16 UTC, merged