feat: lamassu eth recovery script
lamassu/lamassu-server pull request #808
Opened 2021-08-03 17:59 UTC by josepfo

2021-08-03 18:00 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Restoring ETH funds](https://trello.com/c/reiD6Fy0/885-restoring-eth-funds)

2021-08-05 01:20 UTC, chaotixkilla approved these changes

2021-08-06 10:21 UTC, RafaelTaranto requested changes

2021-08-06 10:21 UTC, RafaelTaranto commented on bin/lamassu-eth-recovery.js
> +run(address)
Can we add a bit of a friendly UI in terms of error handling and how to use the script? Take a look at the `lamassu-register` file

We also wanna follow the same standards as other bins in terms of naming and first line of the file, loose the js extension and add the `#!/usr/bin/env node`

2021-08-06 10:21 UTC, RafaelTaranto commented on bin/lamassu-eth-recovery.js
> +run(address)
We also need to add this to package.json, under `bin`

2021-08-18 13:27 UTC, RafaelTaranto approved these changes

2021-08-19 12:03 UTC, merged