Customer custom notes
lamassu/lamassu-server pull request #811
Opened 2021-08-04 00:49 UTC by chaotixkilla

2021-08-04 00:55 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add editable notes section to customer profile page](https://trello.com/c/vWAOREVw/900-add-editable-notes-section-to-customer-profile-page)

2021-08-16 14:42 UTC, josepfo requested changes

2021-08-16 14:42 UTC, josepfo commented on lib/customers.js
> +      ) cn on c.id = cn.customer_id
```suggestion
      LEFT OUTER JOIN (
        SELECT customer_id, content FROM customer_notes
      ) cn ON c.id = cn.customer_id
```

2021-08-26 15:53 UTC, josepfo approved these changes

2021-10-27 09:09 UTC, RafaelTaranto approved these changes

2021-10-27 09:09 UTC, RafaelTaranto commented on migrations/1627868356883-customer-custom-notes.js
> +      content TEXT
Any reason for content allowed as null?

2021-10-27 09:09 UTC, RafaelTaranto commented on lib/new-admin/graphql/resolvers/customer.resolver.js
> +      const token = !!context.req.cookies.lid && context.req.session.user.id
Can't token be false here? And in other places we're doing the same? I would rather have a get token function that returns null and the null is properly handled. I know this probably won't happen but I think it's still the better option here.

2021-12-10 10:41 UTC, merged