Custom SMS
lamassu/lamassu-server pull request #813
Opened 2021-08-04 14:08 UTC by chaotixkilla

2021-08-04 14:08 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Custom SMS notices to customers](https://trello.com/c/igDUi5Ui/899-custom-sms-notices-to-customers)

2021-08-29 21:41 UTC, josepfo requested changes
Looking good!

2021-08-29 21:41 UTC, josepfo commented on lib/plugins.js
> +            const sql = 'update cash_out_txs set notified=$1 where id=$2'
Good chance to uppercase this

2021-08-29 21:41 UTC, josepfo commented on lib/sms.js
> +}
Looks good but these functions seem similar enough so we can define a getCustomSms(phone, event, content) that changes according to the use case (cash out ready or code).

2021-08-29 21:41 UTC, josepfo commented on lib/plugins.js
> +        }
Maybe we should change 'msg' to something like 'smsStructure' since this is an object, what do you think?

2021-08-29 21:41 UTC, josepfo commented on lib/plugins.js
> +        }
Here as well

2021-08-30 19:00 UTC, josepfo approved these changes

2021-09-20 12:20 UTC, RafaelTaranto approved these changes

2021-10-04 08:08 UTC, joshmh requested changes

2021-10-04 08:08 UTC, joshmh commented on lib/plugins.js
> +    return sms.getSms('cash_out_dispense_ready', phone, { timestamp })
I think we should make these keys constants so we'll have them all in one place and guard against typos.

2021-10-04 08:08 UTC, joshmh commented on lib/sms.js
> +        const messageContent = _.reduce((acc, it) => _.replace(`#${it}`, content[it], acc), accMsg, contentKeys)
Will this work for different languages? What if we are inserting numbers and we have to adjust plurals?

2021-11-24 17:42 UTC, merged