Feat: ping time 2
lamassu/lamassu-server pull request #828
Opened 2021-08-30 17:41 UTC by josepfo

2021-08-30 17:42 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backport "Ping time"](https://trello.com/c/IkxRswk9/912-backport-ping-time)

2021-09-01 21:23 UTC, chaotixkilla requested changes

2021-09-01 21:23 UTC, chaotixkilla commented on migrations/1626275844773-add-machine-network-performance.js
> +}
Missing end of file newline

2021-09-07 14:09 UTC, RafaelTaranto approved these changes

2021-09-07 15:42 UTC, merged