Add support for multiple cassettes
lamassu/lamassu-server pull request #830
Opened 2021-09-01 15:35 UTC by chaotixkilla

2021-09-01 15:39 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Work on having multiple cassette boxes](https://trello.com/c/7MTrqh00/925-work-on-having-multiple-cassette-boxes)

2021-09-13 12:05 UTC, josepfo requested changes

2021-09-13 12:05 UTC, josepfo commented on lib/plugins.js
> +    const provisioned = _.reduce(sumTxs, Array(_.size(orderedCassettes)).fill(0), redeemableTxs)
what do you think about doing it this way just to follow the pattern you've been using? 
```suggestion
    const provisioned = _.reduce(sumTxs, _.times(_.constant(0), _.size(orderedCassettes)), redeemableTxs)
```

2021-09-13 12:05 UTC, josepfo commented on lib/plugins.js
> +        }
Can you explain why do we need to throw this?

2021-09-13 12:05 UTC, josepfo commented on lib/plugins/wallet/mock-wallet/mock-wallet.js
> +const CONFIRM_TIME = AUTHORIZE_TIME + 10 * SECONDS
Is this change  intended?

2021-09-13 18:25 UTC, chaotixkilla commented on lib/plugins.js
> +        }
As we're moving away from 2 hardcoded cassettes to a variable number, it's just a sanity check to ensure that we're not using mismatched cassette configs

2021-09-13 20:24 UTC, josepfo approved these changes

2021-10-22 08:59 UTC, merged