feat: move paper wallet only to admin
lamassu/lamassu-server pull request #835
Opened 2021-09-04 23:19 UTC by josepfo

2021-09-05 17:56 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Move paper wallet-only printing to the admin, support the rest of coins](https://trello.com/c/9Li42AQV/934-move-paper-wallet-only-printing-to-the-admin-support-the-rest-of-coins)

2021-09-09 03:20 UTC, chaotixkilla requested changes

2021-09-09 03:20 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Blacklist/Blacklist.js
> +    <>
You can remove the `<>(...)</>` node

2021-09-09 03:20 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Blacklist/Blacklist.js
> +  const enablePaperWalletOnly = complianceConfig?.enablePaperWalletOnly ?? false
You can change line 155 as well, to simplify code

```suggestion
  const enablePaperWalletOnly = !!complianceConfig.enablePaperWalletOnly
```

2021-09-09 03:20 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Blacklist/Blacklist.js
> +                }}
```suggestion
                onChange={e => enablePaperWalletOnly
                  ? addressReuseSave({ enablePaperWalletOnly:  e.target.checked })
                  : setConfirmDialog(true)
                }
```

2021-10-05 22:23 UTC, chaotixkilla requested changes

2021-10-05 22:23 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Blacklist/Blacklist.js
> +                  paper wallets paper wallets will be printed for users, and
`paper wallets paper wallets` on repeat here. And `... means that all only ...` doesn't sound well

2021-10-05 22:23 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Blacklist/Blacklist.js
> +  const enablePaperWalletOnly = !!complianceConfig?.enablePaperWalletOnly
You can change the variable on line 153 to match the `!!` format of this new one. For consistency's sake

2021-10-24 17:33 UTC, chaotixkilla approved these changes

2022-02-04 17:04 UTC, chaotixkilla approved these changes

2022-02-14 16:08 UTC, merged