Fix customer history retrieval
lamassu/lamassu-server pull request #842
Opened 2021-09-09 17:01 UTC by chaotixkilla

2021-09-09 17:01 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bug - Compliance trigger transaction volume](https://trello.com/c/Xq7OxmVl/941-bug-compliance-trigger-transaction-volume)

2021-09-10 19:42 UTC, josepfo approved these changes

2021-09-13 15:07 UTC, RafaelTaranto requested changes

2021-09-13 15:07 UTC, RafaelTaranto commented on lib/tx.js
> +      ((NOT txIn.send_confirmed) AND (txIn.created <= now() - interval $3)) AS expired
Do we really expire cashIn transatcion? Won't the operator already have the customer money at that point and be required to send the coins anyways?

2021-09-13 15:54 UTC, RafaelTaranto approved these changes

2021-09-13 15:54 UTC, RafaelTaranto commented on lib/tx.js
> +      ((NOT txIn.send_confirmed) AND (txIn.created <= now() - interval $3)) AS expired
Just talked about this with Melanie and apparently it expires 0 fiat value cash-in txs. This should be fine!

2021-09-24 09:33 UTC, merged