Fix customer transaction volume
lamassu/lamassu-server pull request #844
Opened 2021-09-10 17:12 UTC by chaotixkilla

2021-09-10 17:12 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bug - Cancelled transactions counting for customer transaction volume](https://trello.com/c/8h42dKmy/945-bug-cancelled-transactions-counting-for-customer-transaction-volume)

2021-09-10 19:25 UTC, josepfo approved these changes

2021-09-13 15:08 UTC, RafaelTaranto requested changes

2021-09-13 15:08 UTC, RafaelTaranto commented on lib/customers.js
> +    coalesce(sum(case when error_code is distinct from 'operatorCancel' then t.fiat else 0 end) over (partition by c.id), 0) as total_spent
Why error_code distinct from 'operatorCancel'? Are all other errors still counting towards the total?

2021-09-15 10:15 UTC, RafaelTaranto approved these changes

2021-09-24 09:35 UTC, merged