Cancel cash-in transactions
lamassu/lamassu-server pull request #845
Opened 2021-09-14 18:00 UTC by chaotixkilla

2021-09-14 18:01 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cancel cash-in transaction in the Admin](https://trello.com/c/NNsLA6uP/950-cancel-cash-in-transaction-in-the-admin)

2021-10-09 12:41 UTC, josepfo approved these changes
Good job!

2021-10-11 16:43 UTC, josepfo approved these changes

2021-10-26 17:43 UTC, RafaelTaranto requested changes

2021-10-26 17:43 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Transactions/DetailsCard.js
> +              })
```js
// create this const and reuse throught the jsx part
const isCashIn = tx.txClass === 'cashIn'
```

Also we can create a single function call here where we pass down the txClass and move the if to ouside of the jsx part of the code.

2021-11-14 23:08 UTC, RafaelTaranto approved these changes

2021-11-14 23:08 UTC, merged