Changes to better support asynclocalstorage on l-a-s-p
lamassu/lamassu-server pull request #847
Opened 2021-09-16 14:27 UTC by chaotixkilla

Based of https://github.com/lamassu/lamassu-server/pull/846

Relevant changes starting on commit https://github.com/lamassu/lamassu-server/commit/2b54ad5fd4b28499d3ac2effe3d5aab4ecb0f37e

2021-09-16 14:31 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add schema selector for l-a-s on Pazuz's side](https://trello.com/c/tkSJbwFu/952-add-schema-selector-for-l-a-s-on-pazuzs-side)

2021-10-12 23:43 UTC, josepfo requested changes

2021-10-12 23:43 UTC, josepfo commented on lib/new-admin/admin-server.js
> +const { session, cleanUserSessions, buildApolloContext } = require('./middlewares')
shoudn't this be 
```suggestion
const { session, cleanUserSessions, buildApolloContext } = require('./middlewares/index')
```

2021-10-13 21:04 UTC, josepfo approved these changes

2021-10-26 17:03 UTC, closed without merging