Pazuz machine pairing
lamassu/lamassu-server pull request #864
Opened 2021-10-05 13:52 UTC by chaotixkilla

2021-10-05 13:53 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate hedging and accounting with the rest of the services](https://trello.com/c/uKaku0j4/973-integrate-hedging-and-accounting-with-the-rest-of-the-services)

2021-11-12 12:06 UTC, josepfo requested changes

2021-11-12 12:06 UTC, josepfo commented on lib/new-admin/middlewares/cleanUserSessions.js
> +  console.log('Clearing expired sessions for schema', schema)
Remove this

2021-11-12 12:06 UTC, josepfo commented on new-lamassu-admin/src/pages/Authentication/Register.js
> +// import base64 from 'base-64'
oh, this was already removed on other PR, rebase should fix it, right?

2021-11-12 13:41 UTC, josepfo commented on lib/db.js
> +  return asyncLocalStorage.run(store, () => store.get('schema'))
shouldn't we use set() instead of get()?

2021-11-16 14:51 UTC, closed without merging