Integrate hedging and accounting with pazuz related screens
lamassu/lamassu-server pull request #873
Opened 2021-10-12 18:05 UTC by chaotixkilla

2021-10-12 18:06 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate accounting and hedging to pazuz admin](https://trello.com/c/gRxTCadG/995-integrate-accounting-and-hedging-to-pazuz-admin)

2021-11-04 13:58 UTC, josepfo requested changes

2021-11-04 13:58 UTC, josepfo commented on new-lamassu-admin/src/pages/Authentication/Register.js
> +// import base64 from 'base-64'
Can we remove this?

2021-11-04 13:58 UTC, josepfo commented on new-lamassu-admin/src/pages/Assets/Assets.js
> +  console.log('operatorData', operatorData)
Remove this as well

2021-11-04 14:03 UTC, josepfo commented
Seems that it has conflicts

2021-11-11 13:16 UTC, josepfo approved these changes

2021-11-17 20:34 UTC, merged