fix: machine unpair breaks the UI
lamassu/lamassu-server pull request #876
Opened 2021-10-12 23:09 UTC by ubavic

Purging db tables upon unpairing from the server will prevent later UI crashes caused by working with a NULL value.

2021-10-12 23:10 UTC, ubavic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Unpair of a machine from server is causing admin page to go blank](https://trello.com/c/VQyrV7kq/1007-unpair-of-a-machine-from-server-is-causing-admin-page-to-go-blank)

2021-10-13 11:23 UTC, RafaelTaranto requested changes

2021-10-13 11:23 UTC, RafaelTaranto commented on lib/pairing.js
> +  return Promise.all([db.none(sql, [deviceId]), db.none(deleteMachinePings, [deviceId]), db.none(deleteMachineHeartbeat, [deviceId])])
This should either be inside a transacion or we should join the 3 deletes into a single query.

2021-10-26 11:44 UTC, RafaelTaranto approved these changes

2021-10-26 11:54 UTC, RafaelTaranto requested changes
We should either stick with prom

2021-10-26 11:54 UTC, RafaelTaranto commented on lib/pairing.js
> +  })
This is doing serialized queries, I don't think it's exactly what we want.

You can unserialize by doing the following:

```js
  return db.tx(t => {
    const q1 = t.none('DELETE FROM devices WHERE device_id=$1', [deviceId])
    const q2 = t.none('DELETE FROM machine_pings WHERE device_id=$1', [deviceId])
    const q3 = t.none('DELETE FROM machine_network_heartbeat WHERE device_id=$1', [deviceId])
    const q4 = t.none('DELETE FROM machine_network_performance WHERE device_id=$1', [deviceId])
    return Promise.all([q1, q2, q3, q4])
  })
```

or


```js
  return db.tx(t => {
    t.none('DELETE FROM devices WHERE device_id=$1', [deviceId])
    t.none('DELETE FROM machine_pings WHERE device_id=$1', [deviceId])
    t.none('DELETE FROM machine_network_heartbeat WHERE device_id=$1', [deviceId])
    t.none('DELETE FROM machine_network_performance WHERE device_id=$1', [deviceId])
  })
```

2021-11-11 18:20 UTC, merged