feat: analyze relevant queries performance
lamassu/lamassu-server pull request #879
Opened 2021-10-15 13:29 UTC by josepfo

2021-10-18 12:38 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Stress test l-s database PT2](https://trello.com/c/lVgRNotn/956-stress-test-l-s-database-pt2)

2021-11-29 00:51 UTC, chaotixkilla requested changes

2021-11-29 00:51 UTC, chaotixkilla commented on test/stress/queries-performance-analyzer.js
> +  const passableErrorCodes = _.map(Pgp.as.text, TX_PASSTHROUGH_ERROR_CODES).join(',')
Small nitpick, but missing newlines to separate functions

2021-11-29 00:51 UTC, chaotixkilla commented on test/stress/queries-performance-analyzer.js
> +}
Would it be a good idea to export the results to a file or something, in case we want to preserve the results over a period of time?

2021-12-10 17:34 UTC, chaotixkilla approved these changes

2021-12-11 19:09 UTC, merged