fix: add unique machine name validation
lamassu/lamassu-server pull request #882
Opened 2021-10-18 10:34 UTC by ubavic

2021-10-18 11:14 UTC, ubavic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Different machines should have different names in the Admin](https://trello.com/c/cw5iEVda/1013-different-machines-should-have-different-names-in-the-admin)

2021-10-24 17:57 UTC, chaotixkilla requested changes

2021-10-24 17:57 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/AddMachine/AddMachine.js
> +      }
This should cut a few lines of code

```suggestion
      (value, context) => !context.options.context.machineNames.includes(value)
```

2021-10-27 16:54 UTC, chaotixkilla approved these changes

2021-10-27 19:49 UTC, RafaelTaranto approved these changes

2021-11-11 18:35 UTC, merged