fix: add validation errors to the update wizard
lamassu/lamassu-server pull request #883
Opened 2021-10-18 12:42 UTC by ubavic

2021-10-25 08:43 UTC, ubavic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Error message missing when editing cash cassettes](https://trello.com/c/DuPdvgaE/1018-error-message-missing-when-editing-cash-cassettes)

2021-10-28 22:26 UTC, chaotixkilla approved these changes

2021-11-02 10:51 UTC, RafaelTaranto requested changes

2021-11-02 10:51 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/Wizard/Wizard.js
> +          )
I think that for min, max and required the YUP default message should be enough.

2021-11-02 10:51 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Maintenance/Wizard/Wizard.js
> +          )
Same as above.

2021-11-12 10:08 UTC, RafaelTaranto approved these changes

2021-11-12 10:08 UTC, merged