Backport database selector flag
lamassu/lamassu-server pull request #886
Opened 2021-10-18 16:23 UTC by chaotixkilla

2021-10-18 16:24 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Backport database selector flag](https://trello.com/c/ZEMWK7tw/1026-backport-database-selector-flag)

2021-10-18 18:23 UTC, josepfo approved these changes

2021-10-26 12:02 UTC, RafaelTaranto requested changes

2021-10-26 12:02 UTC, RafaelTaranto commented on .env
> +LAMASSU_DB=RELEASE
Can we rename this .env to .env.dev or .env.sample and add .env to gitignore?

2021-10-26 12:02 UTC, RafaelTaranto commented on lib/options-loader.js
> +  DEV: _.replace('lamassu', 'lamassu', psqlConf)
Maybe we should add a PROD flag that's exactly the same as dev for now.

2021-10-26 12:02 UTC, RafaelTaranto commented on lib/options-loader.js
> +    config.opts.postgresql = dbMapping(config.opts.postgresql)[process.env.LAMASSU_DB]
Let's default to to PROD.

2021-10-26 12:02 UTC, RafaelTaranto commented on lib/options-loader.js
> +      config.opts.postgresql = dbMapping(config.opts.postgresql)[process.env.LAMASSU_DB]
default to PROD as well

2021-10-26 19:02 UTC, RafaelTaranto approved these changes

2021-10-26 19:02 UTC, RafaelTaranto commented on lib/options-loader.js
> +require('dotenv').config({ path: `.env${process.env.NODE_ENV !== 'production' ? `.dev` : ``}` })
I don't think we should do this either. The idea here is for everyone to just move the .env over and have it not versioned with whatever config they need. Right now I don't think even prod is using NODE_ENV.

2021-10-26 19:02 UTC, RafaelTaranto commented on lib/options-loader.js
> +      process.env.LAMASSU_DB === '' || !process.env.LAMASSU_DB
Isn't `!process.env.LAMASSU_DB` enough?

2021-10-26 19:02 UTC, RafaelTaranto commented on lib/options-loader.js
> +      ]
If htis is all inside the same function can't we decided on the env on top and reuse a db variable?

2021-10-26 19:38 UTC, RafaelTaranto approved these changes

2021-11-11 18:33 UTC, merged