feat: send ping and speedtest URLs to machine
lamassu/lamassu-server pull request #889
Opened 2021-10-20 09:41 UTC by SiIky

2021-10-20 09:41 UTC, siiky commented
![](https://github.trello.services/images/mini-trello-icon.png) [Host a file for ping time tests, re-enable feature](https://trello.com/c/AkV9XoBg/1029-host-a-file-for-ping-time-tests-re-enable-feature)

2021-10-22 00:27 UTC, josepfo requested changes
We need to enable to UI part of this feature as well. See this https://github.com/lamassu/lamassu-server/pull/875/files

2021-10-28 20:18 UTC, josepfo approved these changes

2021-11-02 13:46 UTC, RafaelTaranto requested changes

2021-11-02 13:46 UTC, RafaelTaranto commented on lib/routes.js
> +    size: 8900
I don't think the size is up-to-date here. Also I created a repo to have more control over the blobs. Here's a new link to it:

https://github.com/lamassu/speed-test-assets/raw/main/python-defaults_2.7.18-3.tar.gz

2021-11-12 10:07 UTC, merged