Feat: custom editable fields
lamassu/lamassu-server pull request #895
Opened 2021-10-21 13:48 UTC by josepfo

2021-10-21 13:58 UTC, josepfo commented
![](https://github.trello.services/images/mini-trello-icon.png) [(frontend) Add custom, editable fields to customer profile page](https://trello.com/c/ooj9IUZW/1015-frontend-add-custom-editable-fields-to-customer-profile-page)

2021-10-24 16:52 UTC, chaotixkilla requested changes

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Customers/CustomerData.js
> +const popupImageHeight = 240
```suggestion
const IMAGE_WIDTH = 165
const IMAGE_HEIGHT = 45
const POPUP_IMAGE_WIDTH = 360
const POPUP_IMAGE_HEIGHT = 240
```

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Customers/CustomerData.js
> +  const customEntries = null // get customer custom entries
It's missing the database query here

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Customers/Wizard.js
> +  const stepOptions = getStep(step, selectedValues, liveValues)
I'm not understanding the need for a component to keep the form values in it, can you explain?

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Customers/Wizard.js
> +          </Form>
You can get `values`, `errors` and `touched` on a Formik form with this. Shouldn't be needed a component just for that

```suggestion
          {({ values, touched, errors }) => (<Form className={classes.form}>
            <GetValues setValues={setLiveValues} />
            <stepOptions.Component
              selectedValues={selectedValues}
              {...stepOptions.props}
            />
            <div className={classes.submit}>
              {error && <ErrorMessage>Failed to save</ErrorMessage>}
              <Button className={classes.button} type="submit">
                {isLastStep ? 'Add Data' : 'Next'}
              </Button>
            </div>
          </Form>)}
```

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Customers/components/CustomerSidebar.styles.js
> +      borderRadius: '5px 5px 0px 0px'
I believe you can simplify with this

```suggestion
      borderRadius: [ 5, 5, 0, 0 ]
```

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Customers/components/CustomerSidebar.styles.js
> +      borderRadius: '0px 0px 5px 5px'
Same here

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/action/edit/comet.svg
> +    <desc>Created with Sketch.</desc>
You can remove this line I think, as `title` nodes show up on mouseover

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/data/white.svg
> +    <title>icon/button/data/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/data/zodiac.svg
> +    <title>icon/button/data/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/discount/comet.svg
> +    <title>icon/button/loyalty/comet</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/discount/white.svg
> +    <title>icon/button/loyalty/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/discount/zodiac.svg
> +    <title>icon/button/loyalty/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/photo/white-resized.svg
> +    <title>icon/button/photo/white-resized</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/photo/zodiac-resized.svg
> +    <title>icon/button/photo/zodiac-resized</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/replace/white.svg
> +    <title>icon/button/replace/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/replace/zodiac.svg
> +    <title>icon/button/replace/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/upload-file/white-resized.svg
> +    <title>icon/button/upload-file/white-resized</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/upload-file/white.svg
> +    <title>icon/button/upload-file/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/upload-file/zodiac-resized.svg
> +    <title>icon/button/upload-file/zodiac-resized</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/button/upload-file/zodiac.svg
> +    <title>icon/button/upload-file/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/circle buttons/customer-list-view/white.svg
> +    <title>icon/sf-small/listing/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/circle buttons/customer-list-view/zodiac.svg
> +    <title>icon/sf-small/listing/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/circle buttons/overview/comet.svg
> +    <title>icon/sf-small/overview/comet</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/circle buttons/overview/white.svg
> +    <title>icon/sf-small/overview/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/circle buttons/overview/zodiac.svg
> +    <title>icon/sf-small/overview/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/customer-nav/data/comet.svg
> +    <title>icon/customer-nav/data/comet</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/customer-nav/data/white.svg
> +    <title>icon/customer-nav/data/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/customer-nav/data/zodiac.svg
> +    <title>icon/customer-nav/data/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/customer-nav/overview/comet.svg
> +    <title>icon/customer-nav/overview/comet</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/customer-nav/overview/white.svg
> +    <title>icon/customer-nav/overview/white</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/customer-nav/overview/zodiac.svg
> +    <title>icon/customer-nav/overview/zodiac</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/file/comet.svg
> +    <title>icon/file/zip/comet</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/file/spring.svg
> +    <title>icon/file/zip/spring</title>
Here as well

2021-10-24 16:52 UTC, chaotixkilla commented on new-lamassu-admin/src/styling/icons/file/tomato.svg
> +    <title>icon/file/zip/tomato</title>
Here as well

2021-10-27 23:20 UTC, josepfo commented on new-lamassu-admin/src/pages/Customers/CustomerData.js
> +  const customEntries = null // get customer custom entries
it's not merged yet

2021-10-28 00:00 UTC, josepfo commented on new-lamassu-admin/src/pages/Customers/Wizard.js
> +  const stepOptions = getStep(step, selectedValues, liveValues)
Yeah, not needed here at all. It's some leftovers from another Wizard

2021-10-28 21:08 UTC, chaotixkilla approved these changes

2021-11-16 14:45 UTC, merged