feat: update transaction details on cancel
lamassu/lamassu-server pull request #901
Opened 2021-10-26 12:29 UTC by SiIky

2021-10-26 12:29 UTC, siiky commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cancelling a transaction only gets updated when refreshing the page](https://trello.com/c/Zya3XwXx/1020-cancelling-a-transaction-only-gets-updated-when-refreshing-the-page)

2021-10-28 22:43 UTC, chaotixkilla requested changes

2021-10-28 22:43 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Transactions/Transactions.js
> +  )
This change might break a bugfix from some time ago. I'll post more details in the respective card about it

2021-11-11 03:05 UTC, chaotixkilla approved these changes

2021-11-14 23:43 UTC, merged