Add notifications for multiple cassettes
lamassu/lamassu-server pull request #903
Opened 2021-10-27 14:32 UTC by chaotixkilla

2021-10-27 14:34 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Missing notifications for cassettes 3 and 4](https://trello.com/c/eJcApUpM/1044-missing-notifications-for-cassettes-3-and-4)

2021-10-28 22:17 UTC, josepfo approved these changes

2021-11-11 15:19 UTC, RafaelTaranto requested changes

2021-11-11 15:19 UTC, RafaelTaranto commented on new-lamassu-admin/src/components/editableTable/Row.js
> +    view = it => it?.toString() ?? '—',
What is this for? Can't this logic be moved to the specific place where it's needed?

2021-11-14 22:48 UTC, merged