Add multi cassette on dashboard
lamassu/lamassu-server pull request #904
Opened 2021-10-27 16:27 UTC by chaotixkilla

2021-10-27 16:27 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cassette 3 and 4 missing on dashboard](https://trello.com/c/VUOiirBI/1047-cassette-3-and-4-missing-on-dashboard)

2021-10-28 21:54 UTC, josepfo requested changes

2021-10-28 21:54 UTC, josepfo commented on new-lamassu-admin/src/pages/Machines/MachineComponents/Cassettes/Cassettes.js
> +/* eslint-disable no-unused-vars */
Enable eslint

2021-10-28 21:54 UTC, josepfo commented on new-lamassu-admin/src/pages/Machines/MachineComponents/Cassettes/Cassettes.js
> +
Nice one!

2021-10-28 22:10 UTC, chaotixkilla commented on new-lamassu-admin/src/pages/Machines/MachineComponents/Cassettes/Cassettes.js
> +/* eslint-disable no-unused-vars */
Ah crap, development leftover. Nice catch

2021-11-02 12:14 UTC, josepfo approved these changes

2021-11-11 15:14 UTC, RafaelTaranto approved these changes

2021-11-11 18:23 UTC, merged