Integrate arbitrary compliance
lamassu/lamassu-server pull request #908
Opened 2021-10-27 20:45 UTC by chaotixkilla

2021-10-27 20:46 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Custom requirements](https://trello.com/c/U52YgpVe/817-custom-requirements)

2021-11-10 17:02 UTC, josepfo requested changes

2021-11-10 17:02 UTC, josepfo commented on new-lamassu-admin/src/pages/Triggers/CustomInfoRequests/CustomInfoRequests.js
> +      console.log('Error while removing custom info request')
These are not handy other than debugging, right?

2021-11-10 17:02 UTC, josepfo commented on new-lamassu-admin/src/pages/Triggers/CustomInfoRequests/CustomInfoRequests.js
> +      console.log('Error while editing custom info request')
same

2021-11-10 17:02 UTC, josepfo commented on new-lamassu-admin/src/pages/Triggers/CustomInfoRequests/CustomInfoRequests.js
> +      console.log('Error while adding custom info request')
same

2021-11-11 13:13 UTC, josepfo approved these changes

2021-12-09 19:39 UTC, merged