feat: add Twilio set-up to the Compliance and to the Notifications
lamassu/lamassu-server pull request #926
Opened 2021-11-14 22:47 UTC by ubavic

2021-11-14 22:51 UTC, ubavic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Compliance: turning on SMS compliance should Twilio set-up](https://trello.com/c/EYIGTmmZ/1050-compliance-turning-on-sms-compliance-should-twilio-set-up)

2021-11-17 17:19 UTC, SiIky approved these changes

2022-03-08 16:29 UTC, siiky approved these changes

2022-03-10 14:01 UTC, RafaelTaranto requested changes

2022-03-10 14:01 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Notifications/Notifications.js
> +    })
Doesn't this leave us open to a success in the first save, and a failure in the second one? Why not create a mutation that does both at the same time?

2022-03-10 14:01 UTC, RafaelTaranto commented on new-lamassu-admin/src/pages/Notifications/Notifications.js
> +    })
Same as above

2022-03-14 12:20 UTC, siiky approved these changes

2022-03-14 12:51 UTC, siiky approved these changes

2022-03-14 23:09 UTC, merged