Decouple l-s entrypoint
lamassu/lamassu-server pull request #935
Opened 2021-11-18 08:02 UTC by chaotixkilla

2021-11-18 08:06 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Decouple l-s entrypoint](https://trello.com/c/8iWl8HjH/1091-decouple-l-s-entrypoint)

2021-11-23 15:30 UTC, ubavic requested changes

2021-11-23 15:30 UTC, ubavic commented on tools/build-prod-env.js
> +setEnvVariable('TESTVAR', 'test')
Is this left behind?

2021-11-23 15:30 UTC, ubavic commented on .sample.env
> +## Uncategorized variables
No newline at the end of file

2021-11-23 15:30 UTC, ubavic commented on tools/build-dev-env.js
> +fs.writeFileSync(path.resolve(__dirname, '../.env'), ENV_SAMPLE.join(os.EOL))
Why we do this?
Couldn't  `setEnvVariable` just push to the empty `.env`?

2021-11-23 15:30 UTC, ubavic commented on tools/build-dev-env.js
> +setEnvVariable('POSTGRES_HOST', 'localhost')
Should this be also `${argv.hostname}`?

2021-11-23 15:30 UTC, ubavic commented on tools/build-prod-env.js
> +fs.writeFileSync(path.resolve(__dirname, '../.env'), ENV_SAMPLE.join(os.EOL))
Same as for `build-dev-env.js`

2021-11-23 15:30 UTC, ubavic commented on tools/build-prod-env.js
> +setEnvVariable('POSTGRES_HOST', 'localhost')
Same as for `build-dev-env.js`

2021-11-23 15:30 UTC, ubavic commented on bin/old-lamassu-register
>    console.error('No hostname configured in lamassu.json')
Maybe?
```suggestion
  console.error('No hostname configured in the environment.')
```

2021-11-23 15:30 UTC, ubavic commented on lib/ofac/index.js
>      const message = 'The ofacDataDir option has not been set in lamassu.json'
Maybe?

```suggestion
    const message = 'The ofacDataDir option has not been set in the environment.'
```

2021-11-23 15:30 UTC, ubavic commented on lib/ofac/update.js
>      throw new Error('ofacDataDir must be defined in lamassu.json')
```suggestion
    throw new Error('ofacDataDir must be defined in the environment.')
```

2021-11-23 15:30 UTC, ubavic commented on lib/ofac/update.js
>      logger.error('ofacSources must be defined in lamassu.json')
```suggestion
    logger.error('ofacSources must be defined in the environment.')
```

2021-11-23 15:30 UTC, ubavic commented on lib/db.js
> +
We have same code in a few places atround (`notifications`, `logger`). 
Maybe we should add `PSQL_URL` to the environment (similar as was before)?

2021-11-23 15:30 UTC, ubavic commented on tools/cert-gen.sh
> +node tools/create-dev-env.js
```suggestion
node tools/build-dev-env.js
```

2021-11-23 15:32 UTC, ubavic commented on tools/build-prod-env.js
> +setEnvVariable('TESTVAR', 'test')
This comment refers to `TESTVAR`

2021-11-23 15:34 UTC, ubavic commented on .sample.env
> +## Uncategorized variables
Unix files are expected with a newline. Even if this probably isn't a problem, we should respect this to avoid potential problems in the future.

2021-11-23 19:13 UTC, chaotixkilla commented on tools/build-prod-env.js
> +setEnvVariable('TESTVAR', 'test')
oops, nice catch

2021-11-23 19:15 UTC, chaotixkilla commented on tools/build-dev-env.js
> +fs.writeFileSync(path.resolve(__dirname, '../.env'), ENV_SAMPLE.join(os.EOL))
We're building the `.env` based on the sample `.env` and want to preserve the formatting (comments and overall organization)

2021-11-23 19:16 UTC, chaotixkilla commented on tools/build-dev-env.js
> +setEnvVariable('POSTGRES_HOST', 'localhost')
No, the database will always be running on the local machine per default (as it currently is now)

2021-11-23 19:26 UTC, chaotixkilla commented on lib/db.js
> +
Hmm, I think I prefer the idea to keep the variables separated. Added a constant to the constant files to avoid repeated code

2021-11-23 19:59 UTC, ubavic approved these changes

2022-04-19 11:00 UTC, RafaelTaranto requested changes

2022-04-19 11:00 UTC, RafaelTaranto commented on bin/convert-txs.js
> +
Do we need the path here? Looks like we're importing the var from another file.

2022-04-19 11:00 UTC, RafaelTaranto commented on bin/lamassu-configure-frontcamera
> +require('dotenv').config({ path: path.resolve(__dirname, '../.env') })
This is a problem for production, isn't there a way of starting a server with the dotenv path pre-configured? 

The path for the .env is ~/.lamassu/.env for prod environments.

2022-04-27 14:59 UTC, merged