Replace moment usage
lamassu/lamassu-server pull request #947
Opened 2021-11-23 18:26 UTC by chaotixkilla

2021-11-23 18:29 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace moment.js on the admin react project](https://trello.com/c/7CTMa98U/1095-replace-momentjs-on-the-admin-react-project)

2021-11-24 21:10 UTC, josepfo requested changes

2021-11-24 21:10 UTC, josepfo commented on lib/admin/server.js
> +        return `${row.name} down for ${formatDuration(age)}`
Are we displaying the duration in milliseconds or seconds?

2021-11-24 21:10 UTC, josepfo commented on new-lamassu-admin/src/utils/timezone-list.js
> +  GMT: 'UTC',
Missing ' ?

2021-11-24 21:10 UTC, josepfo commented on new-lamassu-admin/src/utils/timezone-list.js
> +const timezones = {
These labels are supposed to improve UX, right?

2021-11-24 22:45 UTC, josepfo approved these changes

2021-11-24 23:15 UTC, merged