Add cash cassettes wizard to the machine status screen
lamassu/lamassu-server pull request #950
Opened 2021-11-25 17:49 UTC by chaotixkilla

fix: add cash cassettes editing wizard to the counterpart screen on the machine status screen

fix: issue with the cassettes wizard and steps for undefined cassettes

2021-11-25 17:50 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Cash box history showing NaN totals](https://trello.com/c/NsFKICd6/1101-cash-box-history-showing-nan-totals)

2021-11-26 11:30 UTC, SiIky requested changes

2021-11-26 11:30 UTC, SiIky commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +        cassette4: cassette4 ?? 0
You could move this to the `onContinue()` function of the Wizard, after the `parseInt()`.

2021-11-26 11:30 UTC, SiIky commented on new-lamassu-admin/src/pages/Machines/MachineComponents/Cassettes/Cassettes.js
> +        cassette4: cassette4 ?? 0
And this would be unnecessary too, right?

2021-11-29 09:51 UTC, merged