fix: machine unpair (release)
lamassu/lamassu-server pull request #957
Opened 2021-11-26 12:26 UTC by ubavic

2021-11-26 12:30 UTC, ubavic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Machine unpair failing](https://trello.com/c/sy6lzuor/1080-machine-unpair-failing)

2021-11-29 13:31 UTC, chaotixkilla approved these changes

2021-12-01 10:34 UTC, RafaelTaranto requested changes

2021-12-01 10:34 UTC, RafaelTaranto commented on lib/pairing.js
> +      )`, [uuid.v4(), deviceId])
```js
    t.none(`INSERT INTO unpaired_devices(id, device_id, name, model, paired, unpaired)
      SELECT $1, $2, d.name, d.model, d.created, now()
      FROM devices d 
      WHERE device_id=$2`
   , [uuid.v4(), deviceId])
```

2021-12-01 10:34 UTC, RafaelTaranto commented on lib/pairing.js
> +      )`, [uuid.v4(), deviceId])
This should work

2021-12-02 15:00 UTC, merged