Create a bill batching function with machine updates
lamassu/lamassu-server pull request #964
Opened 2021-11-29 23:25 UTC by chaotixkilla

2021-11-29 23:26 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor create batch functions to run on the server side.](https://trello.com/c/AEX5OyEk/1120-refactor-create-batch-functions-to-run-on-the-server-side)

2021-12-09 01:00 UTC, josepfo requested changes

2021-12-09 01:00 UTC, josepfo commented on lib/cashbox-batches.js
> +  if (!_.has(['deviceId', 'cashbox', 'cassettes'], machineContext) && !_.inRange(constants.CASH_OUT_MINIMUM_AMOUNT_OF_CASSETTES, constants.CASH_OUT_MAXIMUM_AMOUNT_OF_CASSETTES + 1, _.size(machineCont
This line seems too long

2021-12-09 01:00 UTC, josepfo commented on lib/cashbox-batches.js
> +      machineContext.cassettes[3],
Do we have 0 as a default value for each cassette? For devices that only have 2 for instance

2021-12-09 01:04 UTC, josepfo commented
Has conflicts

2021-12-10 16:15 UTC, josepfo requested changes

2021-12-10 16:15 UTC, josepfo commented on new-lamassu-admin/src/pages/Maintenance/Wizard/Wizard.js
> +  console.log('AAA', CASSETTE_FIELDS)
You missed this one

2021-12-10 16:15 UTC, josepfo commented on new-lamassu-admin/src/pages/Maintenance/Wizard/Wizard.js
> +const MAX_NUMBER_OF_CASSETTES = 4
Wondering if this should live on l-s/new-lamassu-admin/src/utils/constants.js

2021-12-10 16:15 UTC, josepfo commented on new-lamassu-admin/src/pages/Maintenance/CashCassettes.js
> +          text: 'Cashbox history a',
This is probably an unintentional change

2021-12-10 16:35 UTC, josepfo approved these changes

2021-12-11 19:08 UTC, merged