Implement pazuz ticker
lamassu/lamassu-server pull request #968
Opened 2021-12-01 00:48 UTC by chaotixkilla

2021-12-01 00:48 UTC, chaotixkilla commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create the pazuz ticker plugin](https://trello.com/c/6jGKAvp6/671-create-the-pazuz-ticker-plugin)

2021-12-09 15:35 UTC, SiIky commented on tools/set-env-var.js
> +  const target = ENV_VARIABLES.indexOf(ENV_VARIABLES.find(line => line.match(new RegExp(`^${key}`))))
Using the regex `^${key}=` would better future proof this code. With the current regex, `foo` would also match `foobar`, which is wrong, and leads to the wrong result depending on the order of the keys in the file.

2021-12-09 16:01 UTC, SiIky commented on dev/notify.js
> +const { PSQL_URL } = require('./constants')
Did you mean `'../lib/constants'`?

2021-12-09 16:24 UTC, SiIky commented on lib/plugins/wallet/lnd/lnd.js
> +  return lnd.connect(LND || {})
Is this right? `lnd.connect()` seems to expect an object, but values of environment variables are strings.

2021-12-09 16:30 UTC, SiIky commented on lib/plugins/wallet/monerod/monerod.js
> +const blockchainDir = options.blockchainDir
In the file `lib/blockchain/do-volume.js` you read the blockchain dir from the environment. Is that a different variable, or should this be read from the environment as well?

2021-12-09 16:39 UTC, SiIky requested changes

2021-12-09 16:39 UTC, SiIky commented on tools/build-prod-env.js
> +fs.writeFileSync(path.resolve(__dirname, '../.env'), ENV_SAMPLE.join(os.EOL))
Any special reason to read&write instead of using `fs.copyFile()` or `fs.copyFileSync()`?

2021-12-13 12:08 UTC, SiIky approved these changes
LGTM

2022-05-11 15:07 UTC, merged